### ISSUE TITLE
Can't change scheme

### ISSUE THREAD

**Issue by hrmoller** [consulo/consulo#100]
In Preferences => Editor => Colors & Fonts If I change scheme name and hit OK nothing happens in the editor.

Consulo 1.0 build #621

**Comment by VISTALL** [comment]
Hm. Try change it at root configurable.

Here
![](http://klikr.org/1c3e06f69093e119150b188b18d8.png)

**Comment by hrmoller** [comment]
Hmm got it to work now when ticking 'Show only monospaced fonts'.

However, rendering of font (Source Code Pro) seems to be different.
Same settings (ignore the red underline)
Consulo:
![screenshot 2015-03-13 14 12 58](https://cloud.githubusercontent.com/assets/645472/6638946/39dbdd72-c98b-11e4-9084-259e3c1e1322.png)

Intellij:
![screenshot 2015-03-13 14 13 43](https://cloud.githubusercontent.com/assets/645472/6638949/41ce90f6-c98b-11e4-8900-229583344abc.png)

**Comment by VISTALL** [comment]
Hm. Random bug - for me.

**Comment by VISTALL** [comment]
Maybe fix  - updated. In few minutes 622 will be available

**Comment by VISTALL** [comment]
U can check it at http://must-be.org/vulcan/

**Comment by VISTALL** [comment]
Fix help?

**Comment by hrmoller** [comment]
Nope. But I have gone through my Consulo download history and in build #610 there's no problem but in #618 the font rendering has changed.

#610:
![screenshot 2015-03-14 13 50 10](https://cloud.githubusercontent.com/assets/645472/6651714/1c976602-ca51-11e4-85d7-1493520ca979.png)
#618:
![screenshot 2015-03-14 13 49 26](https://cloud.githubusercontent.com/assets/645472/6651715/241e54da-ca51-11e4-9ccf-bb630f53a08b.png)

Can I download older builds somewhere? Then I can try to track it down...

**Comment by VISTALL** [comment]
There no changes in render. But was changed Java options

https://github.com/consulo/consulo/commit/76fedbcc98e7ee7155c5aff05aba51164764bcc9

I think - was used Apple(or oracle) after this update, your consulo start with another JDK

**Comment by hrmoller** [comment]
Yes. Changing JVMVersion to 1.6* seems to fix it:
<key>JVMVersion</key>
<string>1.6*</string>

**Comment by VISTALL** [comment]
Can u show about screen ('Help->About') for 1.6* and 1.6+ ?

**Comment by hrmoller** [comment]
Sure!
1.6*:
![screenshot 2015-03-14 14 10 12](https://cloud.githubusercontent.com/assets/645472/6651765/e2a6a6ee-ca53-11e4-8cde-b086068b91c5.png)

1.6+:
![screenshot 2015-03-14 14 11 21](https://cloud.githubusercontent.com/assets/645472/6651767/04f79ba4-ca54-11e4-9abb-cfe638cf8033.png)

I didn't know, until now, that I had JDK 1.8 installed. I thought I was on 1.7.

**Comment by VISTALL** [comment]
:smile:

**Comment by VISTALL** [comment]
Bug with color scheme exists?

**Comment by hrmoller** [comment]
No I can't reproduce it now.
Thanks for helping me track it down.
