### ISSUE TITLE
Unity3D/c#

### ISSUE THREAD

**Issue by jjhesk** [consulo/consulo#106]
I just want to make a request from [mentioned](https://plugins.jetbrains.com/wishlist/show?pr=&wid=193) that I really like to have Unity3D support on coding in this IDE. 1+

**Comment by VISTALL** [comment]
U can say it via email :+1: 

Consulo already have C# + Unity support. But implementation is draft - need more testing.

Consulo is not popular due i am developer, not  PR manager.

If u want better support - please give me more feedback.

Regards.
