### ISSUE TITLE
[Unity3D Project C#] Upon typing the 1st character, it starts loading for 2 seconds before IDE responds.

### ISSUE THREAD

**Issue by VansonLeung** [consulo/consulo#108]
It looks like Consulo is trying to find the references of related characters for autocompletion.

Is it just me or you are also experiencing this issue?

I am using Macbook Pro mid-2014 model, Yosemite.

My project has more than 50 CS files inside Assembly-CSharp, including a Spine-csharp library.

**Comment by VISTALL** [comment]
Please read this: https://github.com/consulo/consulo/wiki/Frequently-Asked-Questions

**Comment by VansonLeung** [comment]
Thanks for your quick reply. I didn't look through carefully.

**Comment by VISTALL** [comment]
Np. Try and notify me about results

**Comment by VansonLeung** [comment]
I found that in my Consolas /content   the file is called: idea.vmoptions

**Comment by VansonLeung** [comment]
Set to 2048MB, Much Faster!

**Comment by VISTALL** [comment]
Thanks, name 'idea' is legacy(forgot to change it on mac)

Sorry for that, .NET impl is not optimized too much.
