### ISSUE TITLE
Menu action is triggered whenever arrow key is pressed

### ISSUE THREAD

**Issue by pents90** [consulo/consulo#110]
Navigating a source file using the arrow keys causes the "Navigate" menu item to flash blue. This extra behavior also slows down rapid arrow-key navigation.

**Comment by VISTALL** [comment]
Hi. Can you provide some example? I don't understand what you mean

**Comment by pents90** [comment]
It is as if the menu is being activated by every key press. It flashes "Navigate" for left and right arrow keys, and "Code" for up/down arrow keys. Hopefully this helps. I tried to screen capture it, but couldn't get the screen cap to include the menu bar.

<img width="589" alt="arrowkeysconsula" src="https://cloud.githubusercontent.com/assets/649612/8961174/b0268b90-35e1-11e5-88c6-e0e1178f8955.png">

**Comment by VISTALL** [comment]
Mac :(

Sorry - but i dont have Mac for repeat problem. I leave this issue opened for future.

I will try to repeat in vmware, but i cant say - that i will fix it

**Comment by pents90** [comment]
No prob, understood. It doesn't happen right away, it seems like something triggers it after extended use. So, it's not a super critical problem. Good job on this project!

**Comment by ernestp** [comment]
I've got absolutely weird behaviour today with arrow keys, on each down/up key code is messing, some of lines change order. After i close file, there is no 'Save' dialog and all messing changes applies to file content.

**Comment by pents90** [comment]
@ernestp yes, I have had this happen too, and it seems related to the problem I described because it also causes the menu bar to flash.

**Comment by VISTALL** [comment]
Yeah guys, i known about this problem, but it cant be fixed in a current moment - reason i wrote in previos comment

**Comment by VISTALL** [comment]
Since Consulo 2 released, I close this issue. If repeated - create new issue.

Thanks
