### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by lowolf** [consulo/consulo#112]
When Consulo'll support auto-updating?

**Comment by VISTALL** [comment]
Hi. At current moment - i don't know

**Comment by cupsster** [comment]
WOuld love to have it as it messes up with my system when I click it by accident :P

**Comment by VISTALL** [comment]
For now - no updates about this issue

**Comment by VISTALL** [comment]
closed by https://github.com/consulo/consulo/issues/112
