### ISSUE TITLE
Preferences: Code style - General not loading

### ISSUE THREAD

**Issue by ernestp** [consulo/consulo#114]
![screenshot 2015-08-08 16 33 01](https://cloud.githubusercontent.com/assets/7553589/9149913/616e5d7c-3deb-11e5-9886-4f3cd2e56d82.png)

**Comment by VISTALL** [comment]
And its not help - when u unselect General, and select again?

**Comment by ernestp** [comment]
nop (

**Comment by VISTALL** [comment]
Can u attach log - 

Help -> Show Log in Finder

**Comment by VISTALL** [comment]
For now i cant repeat it

**Comment by ernestp** [comment]
I think it caused IDE exception, I've reported it.

**Comment by VISTALL** [comment]
Yeah

#CEP-1135

**Comment by ernestp** [comment]
In case log can help somehow: https://www.dropbox.com/s/4z0up1x28dhttib/idea.log?dl=1
