### ISSUE TITLE
JB plugin Terminal broken on Windows 10

### ISSUE THREAD

**Issue by elcreator** [consulo/consulo#116]
It's also broken in all JetBrains products https://youtrack.jetbrains.com/issue/IDEA-143300 , but maybe it can be fixed here? Problem related with environment, not plugin itself. http://stackoverflow.com/questions/30425857/not-able-to-type-anything-in-intellij-idea-terminal-latest-version-on-windows-10/31768422#comment51529086_31768422

**Comment by VISTALL** [comment]
Terminal is emulated by their library **jediterm**. Its a library problem(or depend **pty**)

**Comment by VISTALL** [comment]
Obsolete.

Thanks
