### ISSUE TITLE
Project tree: empty nodes

### ISSUE THREAD

**Issue by stgolem** [consulo/consulo#121]
I have imported .sln file on Windows using x32 version of Consulo
After that when i go to "Project files" view i see blank lines and when i scroll the whole area blinks
![2015-08-19-09-45-39-000048](https://cloud.githubusercontent.com/assets/575855/9349466/7de9c58a-4657-11e5-9789-9a8e683b881b.png)

**Comment by VISTALL** [comment]
In project tab - all good? Can you say count of files in project, or give me project example?

**Comment by stgolem** [comment]
In project tab it seems all fine except that it is not usable after VS experience
Count is about 3000 files for 2 projects i have in imported solution
Also there is many folders in project - about 300 total

**Comment by isaac-udy-8i** [comment]
I believe that this has something to do with the fact that the folders are missing their parent folders. This means if you have two folders containing scripts, at the paths "./One/Two/Three/Common", and "./Four/Five/Six/common", there will be two folders next to each other in the project files view, "Common" and "common", with no way to know which each folder is (other than examining the content).

**Comment by VISTALL** [comment]
For now - Consulo don't support Solution View as Visual Studio.  For Unity - it's out of priority due Consulo have support for **.unity, .shader** files. They don't showed in solution view

You can simply navigate to target class via double-shift or cmd+N (ctrl+n), etc

**Comment by VISTALL** [comment]
Outdated
