### ISSUE TITLE
Tabs in the middle of a line are converted to spaces

### ISSUE THREAD

**Issue by cmann1** [consulo/consulo#125]
Even though I have the "Use tab character" option checked, tabs in the middle of a line are converted to spaces, eg:

```c#
int var1         = 0;
//         ^ Pressing Tab here will insert four spaces instead of 1 tab
```

**Comment by VISTALL** [comment]
Please provide language which you used, this construct is valid for C# and Java. Or use
correct repository - consulo-csharp or consulo-java

Thanks

**Comment by cmann1** [comment]
Sorry, I'm using C#.

**Comment by VISTALL** [comment]
Please disable auto-detect indent here


![](http://klikr.org/6e0e0da310ed2b12ea56bd56ccde.png)
