### ISSUE TITLE
Maven plugin issue

### ISSUE THREAD

**Issue by echipachenko** [consulo/consulo#126]
When build multi-module project:
......
.....
com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher clean
-Dmaven.multiModuleProjectDirectory system propery is not set. Check $M2_HOME environment variable and mvn script match.
Process finished with exit code 1

**Comment by VISTALL** [comment]
https://github.com/consulo/consulo-maven/issues/3
