### ISSUE TITLE
Change "Introduce variable" to create specific type instead of "var"

### ISSUE THREAD

**Issue by megamattron** [consulo/consulo#128]
Is there a setting that would cause "introduce variable" to make the variable of the specific type of the expression rather than just "var"? For example, instead of:
```
var i = 1+1;
```
it would know to do:
```
int i = 1+1;
```

Either way, thanks very much for working on this project! Very much appreciated.

**Comment by VISTALL** [comment]
Duplicate https://github.com/consulo/consulo-csharp/issues/301

**Comment by VISTALL** [comment]
Hi - change setting inside here:

![](http://klikr.org/821fac867363ccb245be3c8a3870.png)
