### ISSUE TITLE
Изменение шрифта UI

### ISSUE THREAD

**Issue by dimzon** [consulo/consulo#129]
Не редактора исходного текста а именно UI (меню, деревья) - на нетбуке актуально

**Comment by VISTALL** [comment]
Хай. Вот тут не пробывали ?

![](http://klikr.org/565a892f13dbffa33a939777b6f3.png)

Спасибо

**Comment by dimzon** [comment]
тогда баг - в поиске вводим font - данную вкладку не находит

**Comment by VISTALL** [comment]
Settings сейчас подтупливает, дойду и поправлю - там есть пару багов которые мне нужно исправить.

Извиняюсь

**Comment by dimzon** [comment]
нугет найти не могу откуда позвать...
и вообще в VS референсами как-то удобнее из попап-меню управлять чем в IDEA.

**Comment by VISTALL** [comment]
Я ещё не успел написать в другую задачу. Пока там немного сложный вариант, со временем думаю упростится.

Смена шрифта помогла? Если да - я закрою задачу.

**Comment by dimzon** [comment]
ну баг с поиском font есть. вообще как-то подглюкивает (закладка настроек пустая становится). переключение между закладками лечит. шрифт в итоге поменялся

**Comment by VISTALL** [comment]
Угу - это один из багов на исправления
