### ISSUE TITLE
Tools->Generate JavaDoc для C#/.NET проекта?

### ISSUE THREAD

**Issue by dimzon** [consulo/consulo#130]
Это именно JavaDoc или в зависимости от типа проекта будет доку в правильном виде генерировать? Вообще "ошметки" java отовсюду, например библиотеку из maven(!) предлагает подключить. Теоретически можно конечно через IKVM их цеплять, но это скорее "крайний" случай...

**Comment by VISTALL** [comment]
Понял. Это остатки Java реализации от IntelliJ IDEA

У Вас стоит Java плагин, который добавляет эти действия. 

Пo Java вот сюда - https://github.com/consulo/consulo-java

**Comment by dimzon** [comment]
Может в зависимости от типа проекта блокировать плагины? Чтобы не смущало?
И/или сделать различные "профили" IDE как например PhpStorm PyCharm etc?

**Comment by VISTALL** [comment]
Да это косяк Java плагина, поправимо. C#-пом я редко пока пользуюсь, не вижу очевидных вещей.

**Comment by dimzon** [comment]
Я монодевелоп уже не могу после решарпера и идеи, а на нетбуке винды для VS не стоит. Буду тестером :)

**Comment by VISTALL** [comment]
Плагины в Консуле, не должны влиять друг на друга. 

Но Java реализация, была взята из IDEA - и ей "начихать" на это.

**Comment by VISTALL** [comment]
Если встретится опять Java действия в .NET проекте (и не только) напишите - поправлю.

Вот сюда https://github.com/consulo/consulo-java
