### ISSUE TITLE
[Suggestion][.NET] Update .csproj <ItemGroup> on Script addition/deletion

### ISSUE THREAD

**Issue by Scellow** [consulo/consulo#131]
I'm sharing a porject on linux and windows, and i can't use it on windows, cause Visual Studio dosn't add the scripts i added using Consulo

```XML
 <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Test.cs" />
    <Compile Include="Test.Something\Test.cs" />
    <Compile Include="Config.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
```

It would be cool if Consulo could update the .csproj project file :)

**Comment by VISTALL** [comment]
Moved to Visual Studio plugin repository
