### ISSUE TITLE
Copy and paste file from navigator window doesn't work

### ISSUE THREAD

**Issue by likerRr** [consulo/consulo#132]
Hello! 

I often use PHPStorm and there I can `ctrl+c` on file in the `Project` window and then `ctrl+v` ibid and a new file will be created with content of the copied file. Is it possible to bring the same behavior to Consul? 

For now it just copies file name as string

**Comment by VISTALL** [comment]
C# ?

**Comment by likerRr** [comment]
Any file. Or what do you mean?

**Comment by VISTALL** [comment]
I checked and its work for Java classes and simple files

![](http://klikr.org/a6db0d3046f74ecd8cdda3d1a4b3.png)

Need more info

**Comment by likerRr** [comment]
Oh, you're right. Only C# files don't copy. Why?

**Comment by VISTALL** [comment]
Its a problem **class** node. If C# file showed as C# file - copy is worked

**Comment by likerRr** [comment]
And there are no ways to fix it?

**Comment by VISTALL** [comment]
It will be fixed in a few days

**Comment by likerRr** [comment]
Great, thank you a lot!

**Comment by VISTALL** [comment]
I restored default action - later i will add class rename(to correct name)

**Comment by VISTALL** [comment]
New issue https://github.com/consulo/consulo-csharp/issues/new
