### ISSUE TITLE
Error showing in editor for Class<T> calls where a type argument isnt needed

### ISSUE THREAD

**Issue by Fabi** [consulo/consulo#133]
![bug1](https://cloud.githubusercontent.com/assets/246718/10746617/0a3b0cd0-7c4d-11e5-8191-9b2a7b6b0e84.png)

It compiles, but it shouldn't show an error there....

**Comment by VISTALL** [comment]
Hi. Please use corresponding repository https://github.com/consulo/consulo-csharp/issues in future

**Comment by VISTALL** [comment]
Moved to C# repository
