### ISSUE TITLE
await calls only working with () braces

### ISSUE THREAD

**Issue by Fabi** [consulo/consulo#134]
await calls are only working with () braces around the method call (build itself works fine, only ide error)

![bug2](https://cloud.githubusercontent.com/assets/246718/10746649/58e472d6-7c4d-11e5-8792-8311c6561f41.png)

**Comment by VISTALL** [comment]
Hi. Please use corresponding repository https://github.com/consulo/consulo-csharp/issues

**Comment by VISTALL** [comment]
I found a problem - i will fix this in a few days.

Thanks.
