### ISSUE TITLE
Changes in editor font in OSX don't persist after closing Consulo

### ISSUE THREAD

**Issue by UCh** [consulo/consulo#136]
Steps to reproduce (OSX El Capitan):
- Open Consulo
- Open Preferences (Consulo/Preferences)
- Go to IDE Settings/Editor/Color & Fonts/Font
- Change primary font (Merlo) to any other monospaced font, and choose a different font size (13 for example). In order to do this, you should use a personalised scheme. Pick up anyone an use the "Save as" option to create one.
- Click ok or Apply and close the popup.
- Font is changed as expected.
  -Quit Consulo.
  -Open Consulo.
  -The editor font is set to Merlo size 12 again.

Doesn't happen 100% of the time. Sometime a warning saying internal IDE error appears on to top right corner. Looks like happen more often if you change the font and the size at the same time using Apply, but not 100% sure.

**Comment by VISTALL** [comment]
Looks like fixed in last builds
