### ISSUE TITLE
Installing Git integration plugin does nothing

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#137]
Plugin seems to be downloading, but installation does not happen.

**Comment by VISTALL** [comment]
Check plugin list:

Settings -> Plugins 


And it dont work if u dont enabled it for project(VCS -> Enable Version Control -> Git)

**Comment by AAverin** [comment]
Git is not available under version control by default, "Git Intergration" plugin is required to install.
Attempting to install that plugin does nothing - plugin downloads but is not installed

**Comment by VISTALL** [comment]
Consulo restarted?

Try install plugin by hands. Download it by http://must-be.org/consulo/plugins/download?id=Git4Idea

And drop it into plugin dir (Consulo/plugins/) or to user plugin dir(https://github.com/consulo/consulo/wiki/Paths-to-system-directories here u can get it)

WebServer is too laggy

**Comment by AAverin** [comment]
Manual installation says that plugin is not compatible with current IDE build

**Comment by VISTALL** [comment]
Last plugin build required last consulo build

**Comment by AAverin** [comment]
Manual installation worked on latest Consulo
