### ISSUE TITLE
Some issues with defined symbols by default

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#138]
I'm experiencing an issue when consulo thinks that a symbol is defined when actually it isn't.

The library in question is UniRx, downloaded from assets.

In Observable.Unity.cs file of the library there is a check for "UniRxLibrary" symbol being defined.
https://github.com/neuecc/UniRx/blob/master/Assets/UniRx/Scripts/UnityEngineBridge/Observable.Unity.cs

If "UniRxLibrary" symbol is defined a proper usage would be ObservableUnity.EveryUpdate(), otherwise Observable.EveryUpdate().

When running following code from Unity there are no errors:

    var clickStream = Observable.EveryUpdate()
            .Where(_ => Input.GetMouseButtonDown(0));

        clickStream.Buffer(clickStream.Throttle(TimeSpan.FromMilliseconds(250)))
            .Where(xs => xs.Count >= 2)
            .Subscribe(xs => Debug.Log("DoubleClick Detected! Count:" + xs.Count));

But consulo displays an error saying that EveryUpdate method can not be found.

**Comment by VISTALL** [comment]
Can you attach screenshot?

**Comment by AAverin** [comment]
<img width="694" alt="screen shot 2015-11-01 at 18 29 38" src="https://cloud.githubusercontent.com/assets/1481332/10870259/9fcf63e0-80c6-11e5-8374-07184abff35f.png">

**Comment by AAverin** [comment]
And this code correctly runs in Unity showing no errors during compilation

**Comment by AAverin** [comment]
Opening file with following contents produces error in Consulo, but does not produce any errors in built-in Monodevelop.

using System.Collections.Generic;
using UniRx;
using UnityEngine;

    public class InputManager {

    public IObservable<Vector3> MouseDownStream() {
        return Observable.EveryUpdate()
            .Where(_ => Input.GetMouseButtonDown(0))
            .Select(_ => Input.mousePosition);
    }

    }

**Comment by AAverin** [comment]
Found another issue that might be related to this one.

Methods auto-complete does not seem to work with classes that have symbols inside like

    #if MySymbol
    ...
    #endif

For example, methods auto-complete do not work on the following class: https://github.com/modesttree/Zenject/blob/ab8c926e86236f48f534a6d48debda6c738255b8/UnityProject/Assets/Zenject/Main/Scripts/Main/IInstantiator.cs

**Comment by VISTALL** [comment]
Its preprocessor issue - https://github.com/consulo/consulo-csharp/issues/118

**Comment by AAverin** [comment]
Any estimation on when it will be fixed?
I'm using libraries in my Unity project and with this issue present it's basically impossible to work.

**Comment by VISTALL** [comment]
Preprocessor ignored fully, even when it show as disabled. 

I will check in few days

**Comment by VISTALL** [comment]
This issue is fully Preprocessor problem

https://github.com/consulo/consulo-csharp/issues/118

If u comment line, all will work
Assets/UniRx/Scripts/UnityEngineBridge/Observable.Unity.cs:39

**Comment by VISTALL** [comment]
Sorry. I am already working on fixing Preprocessor, but no success
