### ISSUE TITLE
Typing c# generics handleded by IDE as html tag

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#140]
Typing a generic, like <GameView> automatically adds </GameView> like it's an html tag

**Comment by VISTALL** [comment]
Can you provide simple example? 

(please use C# issue tracker https://github.com/consulo/consulo-csharp)

**Comment by AAverin** [comment]
<img width="585" alt="screen shot 2015-11-02 at 19 58 04" src="https://cloud.githubusercontent.com/assets/1481332/10891069/22c7fd18-819c-11e5-9330-d2e61b9eb3ce.png">

**Comment by AAverin** [comment]
<img width="597" alt="screen shot 2015-11-02 at 19 59 21" src="https://cloud.githubusercontent.com/assets/1481332/10891087/3e9dc428-819c-11e5-85db-4b25496c305e.png">

Typing <GameView> automatically adds </GameView>

Why should I use another tracker?
I use Consulo, so I post issues on Consulo github page.

**Comment by VISTALL** [comment]
Consulo plugins are splitted into different repos. Consulo repo is only platform.


Strange i cant repeat it

**Comment by AAverin** [comment]
I think it happens only when defining a class.
Typing on an empty line does not do autocompletition.

Sorry, I don't know much about how IDE works internally and which plugins do what - I install Consulo as a C#-only IDE, so for me Consulo and Consulo-cShapr is the same thing. Probably for others too.

**Comment by VISTALL** [comment]
Reproduced.


Consulo is independent IDE. It have Java + C# plugins. I am using Java for developing plugins(and on my work), C# for .NET users(and Unity)

**Comment by VISTALL** [comment]
Fixed. Thanks for reporting

**Comment by AAverin** [comment]
Java has a perfectly good support in basic Community Edition IntelliJ, in Pro IntelliJ Idea and Android Studio. In fact, Java is supported so good that Jetbrains have developed their own byte-code based language called Kotlin and are writing parts of the IntelliJ IDE using that language.

Don't see any point in having another fork for Java support.

**Comment by VISTALL** [comment]
IDEA limited by JetBrains. I create new API and many other things for implement some frameworks. Like IKVM .NET

http://vistall.livejournal.com/15453.html

And i have some opensource plugins, which are private. And i will implement another Java plugins in opensource "form"

**Comment by VISTALL** [comment]
And IntelliJ IDEA is Java IDE, u cant disable Java Impl. In Consulo you can install Java, and remove it, and dont broke anything
