### ISSUE TITLE
Using custom unity libraries as a source may result in unability to reference script

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#141]
Having following library installed via unitypackage: https://github.com/thefuntastic/Unity3d-Finite-State-Machine

Following code provides 'StateBehavior not resolved'

    using MonsterLove.StateMachine;

    public class BallMono : StateBehaviour, BallView {
        public class Factory : GameObjectFactory<BallMono> {}
    }

<img width="462" alt="screen shot 2015-11-02 at 20 24 03" src="https://cloud.githubusercontent.com/assets/1481332/10891701/b3f4f91e-819f-11e5-88e8-6fec0d2c037c.png">

Opening same file in Monodevelop does not display any issues.
Code correctly compiles and run by Unity

StateBehaviour class has no symbols defined, so this issue is not related to symbols processing

**Comment by AAverin** [comment]
The issue might be related to git intergration or to custom addition of new files to the projects.
Newly added files are probably not parsed correctly and are displayed with a symbol of empty C# class. 

Modifying such files in any way, even making them an empty class, does not make them visible.

Somehow one of the classes ended becoming visible for the IDE and icon changed from Empty C# class to just C# class - this happened after I modified the file and revered changed via Git integration.

**Comment by VISTALL** [comment]
I think u need invoke Sync Project (can be found in context menu of project
dir)

**Comment by hotovec** [comment]
Sync project doesn't help. Also disabling git plugin changed nothing. I have same issue. 
Invalidate caches and other tricks does not work also. 

https://www.dropbox.com/s/6n9xe8yyn6pdgq4/Screenshot%202015-11-08%2015.43.10.png?dl=0
files marked rounded icon(class) are working ok, without errors. Files marked as C# icons are not working fine. And you are getting missing reference if you are trying use their classes.

There is one workaround you can try.
Just delete .consulo hidden folder from your unity project. And reimport whole unity project to Consulo from scratch. This is working for me.

**Comment by AAverin** [comment]
Well, for me Unity Sync actually helped. Have been working for the last 6 days with no similar issues

**Comment by VISTALL** [comment]
Created separate issue https://github.com/consulo/consulo-unity3d/issues/45
