### ISSUE TITLE
Missing c# plugin

### ISSUE THREAD

**Issue by likerRr** [consulo/consulo#142]
Hello. I've been using Consulo for a while for unity development and yesterday I've reinstalled it, but can't find csharp plugin.

Build 1196

![begin](http://clip2net.com/clip/m182888/559ae-clip-6kb.png?nocache=1)
![begin](http://clip2net.com/clip/m182888/d5d57-clip-3kb.png?nocache=1)
![c# plugin missed](http://clip2net.com/clip/m182888/a1e28-clip-116kb.png?nocache=1)

**Comment by VISTALL** [comment]
Hi. Sorry. I checked - C# plugin build is failed. Working on fix

**Comment by VISTALL** [comment]
I found a problem in 30 min, C# plugin will be available
