### ISSUE TITLE
Using List.Count property in C# results in a strange error

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#144]
List Count property in C# is supposed to return Int value, but when using myList.Count in Consulo I get a strange error

![screen shot 2015-11-08 at 12 37 21](https://cloud.githubusercontent.com/assets/1481332/11020127/7fd7a76a-8615-11e5-95e7-106a03ffaf23.png)

**Comment by VISTALL** [comment]
Looks like https://github.com/consulo/consulo-csharp/issues/313

But it was fixed. Please say C# plugin version

**Comment by AAverin** [comment]
2170

**Comment by VISTALL** [comment]
Looks like this issue obsolete. Please update Consulo & plugins

**Comment by AAverin** [comment]
Fixed only partially.
Calling

```
UnityEngine.Random.Range(0, emptyPositions.Count);
```

still marked as error on latest consulo

**Comment by VISTALL** [comment]
Hi. I created new issue https://github.com/consulo/consulo-csharp/issues/331

Its not simple issue - maybe fixed in a week, or not (i am busy in this month)
