### ISSUE TITLE
IDE no longer lets you generate method

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#145]
Alt+Enter no longer shows an option to add a method on target class.

When writing

```
myClass.myNewMethod();
```

myNewMethod is highlighted in red, but when pressing Alt+Enter on it IDE usually allows to add a method with this name and signature to myClass implementation, supporting both classes and interfaces.

In latest update option to generate method no longer appears.

**Comment by VISTALL** [comment]
C# ?

**Comment by AAverin** [comment]
Yes, C#

**Comment by AAverin** [comment]
Latest Update didn't resolve the issue - generating methods on other classes does not work

**Comment by VISTALL** [comment]
Please provide simple example

**Comment by AAverin** [comment]
```
public class MyClass1 {
        
    }
    
    public class MyClass2 {
        private MyClass1 myClass1;
        
        public MyClass2() {
            myClass1.init();
        }
    }
```


MyClass1 does not have method init(), so init is highlighted in red color. Usually in Intellij products pressing Ctrl+Enter shows a menu, that lets you add missing method on the target class automatically, generating it. This was working in Consulo before, but no longer works.

**Comment by VISTALL** [comment]
All works. What your C# plugin version? Current is **2269** (updating only Consulo is not enough, due it dont contains plugins)

![](http://klikr.org/768ffb40fca3f427ec3cfacbd941.gif)

**Comment by AAverin** [comment]
I don't see update to 2269. I have 2257 now

**Comment by VISTALL** [comment]
i think u need update Consulo

**Comment by AAverin** [comment]
Consulo is 1201 - latest I got on Download link

**Comment by VISTALL** [comment]
Try now - webserver have lags (open plugin list, then right click on C# - reload plugin list)

**Comment by AAverin** [comment]
Generation is fixed, thanks.
A related issue, that was present before.
In the following example generated result should be void init();, not public void init() {}


```

public interface MyClass1 {

    }

    public class MyClass2 : MyClass1 {
        private MyClass1 myClass1;

        public MyClass2() {
            myClass1.init();
        }
    }

```

**Comment by VISTALL** [comment]
I created issue

https://github.com/consulo/consulo-csharp/issues/333

**Comment by VISTALL** [comment]
fixed
