### ISSUE TITLE
Unable to debug complex Reactive methods

### ISSUE THREAD

**Issue by AAverin** [consulo/consulo#151]
I have a problem with more complex reactive calls then usual implemented with UniRx library - debugger doesn't stop on breakpoints in Subscribe.

For example, following code runs correctly, but doesn't stop inside subscribe:

```
Observable.Merge<String>(
            Observable.Return("1"),
            Observable.Return("2"),
            Observable.Return("3")
        ).Subscribe(entry => {
            llogger.log_w(this, entry);
        });
```

While following code stops correctly:

```
inputManager.MouseMoveStream().Select(position => {
            return ProcessRawPosition(position);
        }).Subscribe(position => {
            view.applyPosition(position);
        });
```

**Comment by AAverin** [comment]
MonoDevelop correctly stops inside all Subscribe methods

**Comment by VISTALL** [comment]
can u show where u placing breakpoint? (line)

**Comment by AAverin** [comment]
On lines
```
llogger.log_w(this, entry);
```

and 

```
view.applyPosition(position);
```

When I place breakpoint it shows correctly, but after running project in unity breakpoint changes to disabled.

**Comment by VISTALL** [comment]
Thanks. I will test idk when, due need simple project (i am currently do not have Unity projects)

**Comment by AAverin** [comment]
Isn't Unity a main focus of Consulo?

**Comment by VISTALL** [comment]
No. I am not Unity developer - but i am trying to make unity developers life better :)

**Comment by VISTALL** [comment]
![](http://klikr.org/72677170f0712db157f861cb5086.png)


strange. I can debug at lambda

**Comment by VISTALL** [comment]
If you repeat problem - create new issue
