### ISSUE TITLE
Null-coalescing operator incorrect type

### ISSUE THREAD

**Issue by profelis** [consulo/consulo#152]
Consulo incorrect resolve Null coalescing operator return value.
https://msdn.microsoft.com/en-us/library/ms173224.aspx

Example
``` 
int? a = null;
int b = a ?? 1;  // consulo highlight red
```
https://gyazo.com/0ad1440ad321ddd4f8b8db82af83b74c

**Comment by VISTALL** [comment]
Its already fixed. Please update C# plugin

For next C# issue report here https://github.com/consulo/consulo-csharp
