### ISSUE TITLE
Misleading docs on increasing Consulo heap size (Mac)

### ISSUE THREAD

**Issue by hrmoller** [consulo/consulo#153]
I find the docs on increasing the Consulo heap size (found in tha [F.A.Q.](https://github.com/consulo/consulo/wiki/Frequently-Asked-Questions)) a bit misleading.

Instead of editing `idea.vmoptions` in `/Applications/Consulo.app/Contents/bin` the should be copied to ~/Library/Preferences/ConsuloData where it should be edited to have any effect.

[The docs found at jetbrains](https://www.jetbrains.com/idea/help/increasing-memory-heap.html#d1366197e127) explains it pretty well.

All the above counts for Mac only. I can't tell how it works on a PC.

**Comment by VISTALL** [comment]
I am idk how it works. JB was changed their MacOS runner, and this change i am not merged (due i dont want break MacOS distribution)

As i known - any user can edit wiki

**Comment by hrmoller** [comment]
Anyone can edit the docs and if it's OK with you I will edit the docs whenever I have the time.

**Comment by VISTALL** [comment]
changed in Consulo 2.0. Doc updated
