### ISSUE TITLE
NoClassDefFoundError: org/consulo/module/extension/ui/ModuleExtensionWithSdkPanel

### ISSUE THREAD

**Issue by Sipaha** [consulo/consulo#154]
When I try to update plugins for Consulo I have got exception:

[Exception in Consulo core.txt](https://github.com/consulo/consulo/files/79384/Exception.in.Consulo.core.txt)

and after restart plugins still have old version.

I deleted .ConsuloData folder, downloaded last versions of plugins and on startup I got this exceptions in my project:

[plugins_exeptions.txt](https://github.com/consulo/consulo/files/79385/plugins_exeptions.txt)

I deleted .consulo folder in my project (Unity) and tries to import it again, but I have got this:

[import_unity_project.txt](https://github.com/consulo/consulo/files/79389/import_unity_project.txt)

**Comment by VISTALL** [comment]
Please update plugins. You have too old plugins:)

You need search Plugin Directory(here https://github.com/consulo/consulo/wiki/Paths-to-system-directories), delete all plugins, and install new Unity plugin with dependencies

**Comment by Sipaha** [comment]
>delete all plugins, and install new Unity plugin with dependencies

It works! Thank you! But I don't understand why deleting '.ConsuloData' directory did not help to me before. Anyway, thank you very much for fixes of the last few days. Now Consulo is the best IDE for Unity in my opinion. Good job! :)

**Comment by VISTALL** [comment]
Okey. Thanks
