### ISSUE TITLE
Consulo stucks on outdated index

### ISSUE THREAD

**Issue by likerRr** [consulo/consulo#155]
Hello.

I've got strange issue. I run Consulo and when I try to write some code it gets stucked. It doesn't "not responding" it just doesn't react on any actions. I tried install fresh consulo, update all plugins, run as administrator, run both x32 and x64 versions, install JDK separately but nothing has changed. It continue stucks every time when I start typing something. 

**Important note**: when I just open it and scroll the code for viewing or open files - it works normally, even I can type whitespace somewhere in file, but when I write real code it gets stucked.

Windows 10, last updates
![about window](http://clip2net.com/clip/m182888/a5fd3-clip-11kb.png)
Process manager when Consulo stucks:
![process manager](http://clip2net.com/clip/m182888/f82c0-clip-4kb.png)

**Comment by VISTALL** [comment]
Can you attach idea.log and thread dump log from


https://github.com/consulo/consulo/wiki/Paths-to-system-directories  (log directory)

**Comment by likerRr** [comment]
[idea.log.txt](https://github.com/consulo/consulo/files/93493/idea.log.txt)
[20160117-194157.ZIP](https://github.com/consulo/consulo/files/93496/20160117-194157.ZIP)

**Comment by VISTALL** [comment]
Try to invalidate cache(File -> Invalidate)

**Comment by likerRr** [comment]
You know... it works! Thank you very much!

**Comment by VISTALL** [comment]
I am reopen this issue, due need more correct handling **outdated stubs** - not block IDE
