### ISSUE TITLE
Items in an excluded folder are still indexed

### ISSUE THREAD

**Issue by jharrison63** [consulo/consulo#156]
When you exclude a folder in the project, it still indexes the files; this can take a huge amount of time on large projects with many assets (thousands of files).

Even with a larger heap size it can take forever to index, because it is trying to index files that you are trying to exclude.

Ideally, scanning files should ignore excluded folders so this step can be much shorter.

**Comment by VISTALL** [comment]
You excluded Assets folder?

**Comment by relative63** [comment]
No, I am attempting to exclude a folder that we contain all of our animations in -- e.g. 'Assets/Bundles/Animations'.

**Comment by jharrison63** [comment]
No, I am attempting to exclude a folder that we contain all of our animations in -- e.g. 'Assets/Bundles/Animations'.

**Comment by VISTALL** [comment]
Oh its not good. All excluded files will be removed on Project Sync. Can you say total size of directory, and count of all files in this directory. I want to reproduce

**Comment by jharrison63** [comment]
Here is the folder I am trying to exclude, I tried just excluding the entire Bundles folder (since there is no code in here, no reason for me to index it).

![screen shot 2016-02-10 at 9 44 46 am](https://cloud.githubusercontent.com/assets/8700938/12956067/f738113c-cfda-11e5-99b8-670f32210fa0.png)

This is the entire Client directory.

![screen shot 2016-02-10 at 9 42 25 am](https://cloud.githubusercontent.com/assets/8700938/12956018/b2ec286a-cfda-11e5-87a1-5a1efbdac138.png)
