### ISSUE TITLE
Consulo uses high performance GPU on OS X

### ISSUE THREAD

**Issue by h0rdak** [consulo/consulo#157]
NSSupportsAutomaticGraphicsSwitching with a value of true should be present in Info.plist to allow use of integrated GPU.

There is however also a bug in Java causing this to fail, fix should be in 8u76 ( https://bugs.openjdk.java.net/browse/JDK-8041900 )

**Comment by VISTALL** [comment]
You can use this JDK for running Consulo

**Comment by h0rdak** [comment]
Which JDK? 8u76? It's in early access, I'm not going to bother installing it until release.

NSSupportsAutomaticGraphicsSwitching still should be added to Info.plist

**Comment by VISTALL** [comment]
Sorry - i dont have device with Mac, and cant say - its good fix or not. Its a main problem. Most users work on Mac, and they did not reported anything like this. 

Anyway - thanks for report, i will read more about this at morning

**Comment by VISTALL** [comment]
Added
