### ISSUE TITLE
New classes that created externally(VCS update) are not resolved

### ISSUE THREAD

**Issue by vlasas** [consulo/consulo#158]
Consulo #1277 with the latest plugins, Linux.

C# Unity3D imported project.
After VCS update, all new classes that are created within that update:
 - marked red ("'ClassName' is not resolved") in source code that using them
 - are not accessable for navigation from source code (Ctrl-B, goto declaration),
got "Cannot find declaration to go to".
 - have no working navigation in source code of those files at all

Usually I reimport project to got all classes accessable, but it overrides .consulo and some settings become lost.  ( File/Import project...; Import Project from Unity3D; ... )

**Comment by VISTALL** [comment]
Use Sync project (you can read about it here https://github.com/consulo/consulo-unity3d/wiki/3.-Troubleshooting)
