### ISSUE TITLE
Named parameters e.g. for Actions shows up as an error.

### ISSUE THREAD

**Issue by johanneskraem3r** [consulo/consulo#159]
See the following code. It does not find "DoSomething" 

```csharp
using System;
using UnityEngine;
   
    public class ActionTest {

        public event Action action;

        public void test() {
            this.SetAction(action: DoSomething);
        }

        public void SetAction(Action action) {
            this.action = action;
        }

        private void DoSomething() {
            Debug.Log("Done something!");
        }
    }
```

When I change the line

`this.SetAction(action: DoSomething);`

to

`this.SetAction(DoSomething);`

...it works.

But I do want to use named parameters.

**Comment by VISTALL** [comment]
Hi. Thanks. I will check.

PS. For C# please use another [repository](https://github.com/consulo/consulo-csharp)

**Comment by VISTALL** [comment]
Fixed. You can update C# plugin after one hour

**Comment by johanneskraem3r** [comment]
Sweet -- thanks a lot! 
Very impressed by your turnaround time!

:-)

**Comment by VISTALL** [comment]
Can you say Consulo build? (C# plugin not needed) For info

**Comment by johanneskraem3r** [comment]
#1273

**Comment by VISTALL** [comment]
Oh. Be care with last Consulo build & plugins. Think you need backup Consulo and Plugins(you can found them here https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

Some guy reported me a problem with last builds, but i cant reproduce it

**Comment by johanneskraem3r** [comment]
What should I do? 
Backup both Consulo and Plugins? And then after the update? Copy those files back? Or what?

**Comment by VISTALL** [comment]
Backup. And them update all. If you found some issues with Consulo(random exceptions) - rollback, and report me.

**Comment by johanneskraem3r** [comment]
Just updated to #1278. I can confirm that it works now. I had no problems during updating.

**Comment by VISTALL** [comment]
Thanks!
