### ISSUE TITLE
Reformatting code changed with update.

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo#164]
i have the following code
  http://prntscr.com/ad6kv9

when i press reformat code it breaks like this:
http://prntscr.com/ad6l52

i can't find a way to keep the code like in the 1st image when i reformat. i have set blank lines to 0 and in general my setting used to keep the code tight but now it doesn't work when i reformat. any advice on how to solve (from code format) or is this Consulo related? Sorry if i posted on wrong forum/thread.

**Comment by VISTALL** [comment]
Not matter:) But for future C# problems report here https://github.com/consulo/consulo-csharp/issues

I will check

**Comment by VISTALL** [comment]
Fixed.

Thanks
