### ISSUE TITLE
Editor recognize linq C# statements as errors

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#165]
<img width="1436" alt="screen shot 2016-03-12 at 6 15 48 pm" src="https://cloud.githubusercontent.com/assets/689092/13727890/1b938776-e905-11e5-83e0-cda5e8178efb.png">

**Comment by VISTALL** [comment]
Hi. Can you create simple code for reproduce?

**Comment by VISTALL** [comment]
Reproduced.
