### ISSUE TITLE
Editor doesn't recognize generic type without args<>,<,>,<,,>...

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#166]
<img width="471" alt="screen shot 2016-03-12 at 4 33 33 pm" src="https://cloud.githubusercontent.com/assets/689092/13727893/49ca988c-e905-11e5-8cc8-e1dddede625e.png">

**Comment by VISTALL** [comment]
Thanks. Fixed.


PS: please you C# repository for reporting next issue https://github.com/consulo/consulo-csharp/issues
