### ISSUE TITLE
Prioritizing full functionality of watchers and expression editor (Not supported)

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#168]
<img width="1436" alt="screen shot 2016-03-09 at 12 21 29 pm" src="https://cloud.githubusercontent.com/assets/689092/13728024/b4e5469a-e909-11e5-837b-76b04a674e61.png">

**Comment by VISTALL** [comment]
Can you say C# plugin version? From here(where SNAPSHOT)

![](http://klikr.org/ad026f99dfc4ed2ad13043db3651.png)


Looks like i already fixed this issue.

**Comment by winalex** [comment]
I updated and recheck again. Be patient. :)

**Comment by VISTALL** [comment]
You need update .NET plugin too (better call About -> Check For Updates)

**Comment by winalex** [comment]
Yeah I'm updating everything always :)

**Comment by VISTALL** [comment]
Can you report next issues here ? https://github.com/consulo/consulo-csharp/issues 

Its really hard to find correct issues of C# plugin

**Comment by VISTALL** [comment]
I will close this issue due i cant reproduce. If you reproduced please report it here 

https://github.com/consulo/consulo-csharp/issues
