### ISSUE TITLE
Navigating in list with down arrow doesn't move selection in list but move the code 

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#171]
<img width="876" alt="screen shot 2016-03-16 at 10 47 41 am" src="https://cloud.githubusercontent.com/assets/689092/13809191/d5fe2fb0-eb69-11e5-95b1-13c225c03c3d.png">
<img width="868" alt="screen shot 2016-03-16 at 10 47 47 am" src="https://cloud.githubusercontent.com/assets/689092/13809195/d98fd73c-eb69-11e5-9e67-9d7abb96d0e5.png">

**Comment by WeslomPo** [comment]
I have this issue too. Very disappointed. Only reloading can fix that :(. Randomly appears when delve into the settings. I could not find the exact way to reproduce the bug :(.

**Comment by VISTALL** [comment]
as i undestand - completion popup is not focused?

**Comment by winalex** [comment]
Then make it Modal popup :)

**Comment by VISTALL** [comment]
If - i correct, its bug - and i will fix it

**Comment by VISTALL** [comment]
Can you say steps - how repeat ? (for now i cant repeat)

**Comment by VISTALL** [comment]
Create gif with licecap for example

**Comment by WeslomPo** [comment]
Hi!
Here are a video
https://monosnap.com/file/s5vUmN8qcVX8L1FV2cbyt5QTQRVCSc
Много раз переключался между окнами (unity<-->consulo) потом решил поискать в меню способ отсортировать строки, зашел в edit - ничего не нашёл, нажал на редактор, подумал что найду что нибудь в Code нажал туда, но и там ничего нет, переключился на Unity, скопировал строки там, вернулся вставил, нажал вверх строки поменялись местами. И это никак не отключается. Плюс я заметил что почему-то срабатывает меню code.

**Comment by WeslomPo** [comment]
Попробовал выбрать пункт меню "переместить строку вверх", теперь в обе стороны перемещаются строки. Клавиатура нормальная - не глючная. Все кнопки хорошо работают. Если набрать компбинации на клавиатуре он срабатывают, но глюк всё равно остаётся. Помогает только перезагрузка.

**Comment by WeslomPo** [comment]
Хей-хей! Поймал!
http://take.ms/utfKP
Move Line Down - гарантированно вызывает глюк и Up тоже.

**Comment by VISTALL** [comment]
Окей посмотрю возможно завтра, если по работе не завалят

**Comment by VISTALL** [comment]
С первой попытки у меня не получилось повторить, но это сегодня

**Comment by WeslomPo** [comment]
Может проблема только в определённой ОС случается? У меня MacOS X

**Comment by VISTALL** [comment]
Угу возможно(ибо я проверял на Винде, мака у меня нету).

Можно версию mac и java --version с консоли

**Comment by WeslomPo** [comment]
![image](https://cloud.githubusercontent.com/assets/310008/13856734/03ae65c0-ec90-11e5-90b7-3c9363cb7369.png)

**Comment by VISTALL** [comment]
Спасибо - попробую повторить. На деле за все время использования, такой баг не встречал

**Comment by VISTALL** [comment]
Пока что не повторяемо

**Comment by WeslomPo** [comment]
В этот раз в меню не лазил, просто между вкладки переключался, стал реагировать на кнопки влево вправо а не вверх/вниз. Я увидел что в консуло случилась какая-то ошибка - послал отчёт и вот записал видео:
http://take.ms/NAaV5
Где-то в другом месте глюк...

**Comment by VISTALL** [comment]
Ошибку я увидел - поправлю но увы это другое. 


> А вообще консуло сбилдить -- сложно?
вообще не сложно , но нужно иметь вот это (https://github.com/consulo/consulo/wiki/Plugin-Development-Starter-Guide)

А зачем ?

**Comment by WeslomPo** [comment]
"Во славу сатаны конечно же." xD
Интерес и любопытство... раз у меня этот глюк так легко вызывается, может получится найти в чём причина :).

**Comment by VISTALL** [comment]
Я всегда доступен и могу ответить на любые вопросы:)

**Comment by winalex** [comment]
Ur chating to much :D. Focus on Watcher and Expression doesn't work still.

**Comment by VISTALL** [comment]
But problem with **Stack is not valid fixed** ? You didnt do reply in another issue

**Comment by Misuno** [comment]
Возникает та же фигня, тоже макось. Попробую отловить шаги повторения.

**Comment by Misuno** [comment]
В этот раз случился схожий баг, но по-другому. При нажатии стрелок крусор начал прыгать между объявлениями функций. Ощущение, что IDE получает ложный сигнал о том, что зажата какая-то кнопка.

**Comment by VISTALL** [comment]
i will close this issue. Reopen this issue - if reproduced again with Consulo 2.0
