### ISSUE TITLE
Reformat according to style is not applied in templates

### ISSUE THREAD

**Issue by MarcAtPlumbee** [consulo/consulo#172]
In the following screenshot, you can see that I've checked the box to Reformat according to style.
![screen shot 2016-03-23 at 17 36 29](https://cloud.githubusercontent.com/assets/1300813/13994682/d62f011c-f11d-11e5-8f9d-1b371e7df1ad.png)

This does not appear to work when I use the template, and then need to call 'Format Code' afterwards.

Cheers,
Marc Trepanier

**Comment by VISTALL** [comment]
Hi. Thanks for reporting. I will check tomorrow

**Comment by VISTALL** [comment]
Fixed. But i think - need use single Create C# file, without duplicate action.

I will think about it tomorrow

**Comment by VISTALL** [comment]
Hi. Now C# templates can created via **Create C# File** action.

You can select it here 

![image](https://cloud.githubusercontent.com/assets/542934/14011099/b2e19c8a-f1ac-11e5-9872-6cf79b2aaf14.png)
