### ISSUE TITLE
Selecting code in same position that is in horizontal tab cause tab moving

### ISSUE THREAD

**Issue by WeslomPo** [consulo/consulo#174]
Выбор кода в той же позиции что и горизонтальный вкладка заставляет перемещаться вкладку.
Mac Os X. Я даже видео записал чтобы понятно было :).
https://monosnap.com/file/W3cWcvBXWGjgr3OumcaURYRWrklS6m

**Comment by VISTALL** [comment]
Забавно. И как обычно Mac, хоть бы раз на Win дали баг. Попробую повторить

Спасибо

**Comment by WeslomPo** [comment]
Где работаю работаем.. Под маком для Unity редакторов такого же уровня - нету. Я всё что нагуглил попробовал - ерунда глючная, а под виндой хотя бы VS есть.

**Comment by VISTALL** [comment]
Повторил на Винде

**Comment by VISTALL** [comment]
Поправил.

А как же Rider? )

**Comment by WeslomPo** [comment]
А кто это? Не слышал о таком ;(

**Comment by VISTALL** [comment]
https://www.jetbrains.com/rider/

**Comment by WeslomPo** [comment]
Сыроват и денег стоит xD

**Comment by VISTALL** [comment]
Ясно. Спасибо за ответ
