### ISSUE TITLE
Auto comment on function got screwed

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#176]
```csharp
        //
        // Methods
        //


     / <summary>
        ////
        /// </summary>
        /// <param name="edge"></param>
        public override void Disconnect(UnityEditor.Graphs.Edge edge)
```

So If you have something like this
     
```csharp
        //
        // Methods
        //

        <caret>
        public override void Disconnect(UnityEditor.Graphs.Edge edge)
```

Hit three times /// over Disconnect, comment get in conflict with // Methods

**Comment by VISTALL** [comment]
Can you format second block?

**Comment by winalex** [comment]
?

**Comment by VISTALL** [comment]
I don't undestand how reproduce it(because i don't correct example)

**Comment by VISTALL** [comment]
/<caret> <summary>
    ^ here caret and tap twice slash ?  I can't read mind

**Comment by winalex** [comment]
<img width="1120" alt="screen shot 2016-03-30 at 9 52 28 am" src="https://cloud.githubusercontent.com/assets/689092/14135348/45e3bfea-f65d-11e5-9550-49e487242246.png">
//
// Methods
//

^ <--Here. 
void Method(){}

**Comment by winalex** [comment]
Big issue with debugger I couldn't find it? I sent you sample code and 2 videos. Did you also couldn't so you just close it. :D.

**Comment by VISTALL** [comment]
No - i can't reproduce it. I didn't close issues with some examples (but closed with torn piece of code)

**Comment by winalex** [comment]
Where is the issue then? It has 2 full file source code and 2 videos.? I can't find it.

**Comment by VISTALL** [comment]
First 

https://github.com/consulo/consulo-dotnet/issues/69

Second 

https://github.com/consulo/consulo-csharp/issues/394

Third

https://github.com/consulo/consulo-csharp/issues/393

**Comment by winalex** [comment]
Pls focus on them this are makeup.

**Comment by VISTALL** [comment]
I tried to reproduce. For now i have no idea how reproduce it. Strange first bug - really strange. Maybe i am bad as Unity Developer :D

**Comment by winalex** [comment]
You know that Awake and ... rest of the methods are wired/reflected runtime(by name)

**Comment by VISTALL** [comment]
I known that. And they paused inside other projects (not my). But when i trying to create classes (and attach to scene) and then debug - breakpoints is not work(most of them).

**Comment by WeslomPo** [comment]
Is that issue about that annoying summary comment, that on following video?

https://monosnap.com/file/oaJiwgviO8wVdBRqw6F89gqetXtItE

Can I some how disable summary comment at all?

**Comment by winalex** [comment]
Yes that's it
