### ISSUE TITLE
Created new class isn't formatted.

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#178]
```
namespace 1_WinxProduction.Editor { public class MyClass { }
}
```
instead:
```
namespace 1_WinxProduction.Editor { 
    public class MyClass { 
  }
}
```

**Comment by VISTALL** [comment]
I will check after work. Looks like regeression after my last fix in this code

**Comment by VISTALL** [comment]
Can't reproduce. Please export settings(File->Export Settings...) and say what code style you are using

**Comment by winalex** [comment]
[settings.jar.zip](https://github.com/consulo/consulo/files/197118/settings.jar.zip)

**Comment by VISTALL** [comment]
As i saw - you dont use any codestyle ?

**Comment by winalex** [comment]
Default

**Comment by VISTALL** [comment]
Why you don't said - that you had parsing errors. Rename folder - all all will be ok. I think need some correction for namespace generation

**Comment by winalex** [comment]
Namespace generation for Unity project isn't correct, and I need to fix in manually beside formatting. 
For "Editor" should not go from root folder by find all "Editor" folder and namespace goes from there down. 
`namespace 1_WinxProduction.Editor.ws { public class MyClass { }
}`

should be 
`namespace ws { public class MyClass { }
}`
where hierachy is "Assets/1_WinxProduction/Editor"
With the runtime scripts is even more complex they can be in "Script" folders or/and everywhere
If I uncheck "Reformat according to style" (First how to select style there are Default and Project) formatting is ok.

**Comment by VISTALL** [comment]
about Unity namespace generation -> https://github.com/consulo/consulo-unity3d/issues/69
