### ISSUE TITLE
Add breakpoints dropdown list showing summary as options

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#180]
<img width="1435" alt="screen shot 2016-04-01 at 12 21 06 pm" src="https://cloud.githubusercontent.com/assets/689092/14205750/f9838286-f80d-11e5-8d10-01a24df0da75.png">

When I select summary, first line in drop down. It position breakpoint correctly last line in code from image

**Comment by VISTALL** [comment]
Oh. Wrong offset for popup

**Comment by winalex** [comment]
How can I see actuall .dll code and not //code compiled  as I can do in MonoD?

**Comment by VISTALL** [comment]
![image](https://cloud.githubusercontent.com/assets/542934/14206448/e0a4e440-f81b-11e5-87f1-4a0c7d7da39c.png)

?

**Comment by winalex** [comment]
Go to some Unity Class and go into declaration. You can't see implementaton

**Comment by VISTALL** [comment]
![image](https://cloud.githubusercontent.com/assets/542934/14206620/1507be14-f81d-11e5-9d4c-b173fdbc7bd0.png)

And no. Maybe we can attach C# sources from open-source implementation(https://bitbucket.org/Unity-Technologies)  

But not all libraries is opened

**Comment by winalex** [comment]
I keep older version of MonoDevelop
<img width="1435" alt="screen shot 2016-04-01 at 2 27 48 pm" src="https://cloud.githubusercontent.com/assets/689092/14206808/003f454e-f816-11e5-9123-b839b9a78f0a.png">

Don't know what have done with the new versions, but they close that option. (So with the older MD I open new .dlls and Mono.Cecil do the fun) So I think some compiler debugger option is set?

**Comment by VISTALL** [comment]
I think you have decompiler inside. For now - decompiler is out of poll

**Comment by winalex** [comment]
I can't live without it :8ball:

**Comment by VISTALL** [comment]
Idk for now. Need intergrate dotPeek or ILSpy into .NET plugin, and change language/debugger support for it. Not easy task

**Comment by winalex** [comment]
I think I have enter source once from temp folder which is hidden :)
