### ISSUE TITLE
Using shows unused if needy disabled by preprocessors

### ISSUE THREAD

**Issue by WeslomPo** [consulo/consulo#183]
Using shows unused if needy disabled by preprocessors.
![image](https://cloud.githubusercontent.com/assets/310008/14311088/93f77746-fbf6-11e5-8bcc-6bf20633bb7e.png)

"AndroidGallery" need "Utils" using.

I was glad that consulo now shows unused the usings. I was delete in a couple of places and to commit, as well as builds a device started shows up error ; ( sadness, melancholy

- IDE build number: 1300
- Java version: 1.80_40
- OS name and version:  Max OS X El Capitan 10.11.3

**Comment by VISTALL** [comment]
Please read contributing guide. C# problems need report here: https://github.com/consulo/consulo/issues/183

As about that problem. It can't be fixed. Due disabled block is not parsed and do not provided any resolve information. 

Normally - that using need be hidded inside preprocessor block too

**Comment by WeslomPo** [comment]
Ok, as I think. 

Sorry, next time I try to make issue correctly :) I added the information that you requested to add, I can study

**Comment by VISTALL** [comment]
ops.

https://github.com/consulo/consulo-csharp

**Comment by VISTALL** [comment]
I think it can be part of https://github.com/consulo/consulo-csharp/issues/396

But it really hard to implement
