### ISSUE TITLE
What you think of pluggin to Kite or implementing similar functionality?

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#184]
https://kite.com
https://github.com/kiteco/plugins

**Comment by VISTALL** [comment]
I think i can convert intellij plugin. But i will don't add it to current plugin list(only i'ill give you plugin build)

**Comment by VISTALL** [comment]
https://github.com/VISTALL/kiteco-plugins/blob/master/ConsuloKite/kite.zip

**Comment by winalex** [comment]
How can I install this?

**Comment by VISTALL** [comment]
Unzip into

~/Library/Application Support/ConsuloData
