### ISSUE TITLE
No autocompletion in braces

### ISSUE THREAD

**Issue by theshock** [consulo/consulo#185]
- IDE build number: `1.0 #1322`
- Java version: `1.8.0_51`
- OS name and version: `Windows 7`

Source code:
```cs
using System.Collections.Generic;
using UnityEngine;

public class NatureMaterials : MonoBehaviour {
	private Material GetRandomMaterialFrom (List<Material> materials) {
		materials./*works_correctly_here*/;
		return materials[Random.Range( 0, materials./*fails_here*/ )];
	}
}
```

1. If try to Ctrl+Space out of brackets everything works correctly:
![autocomplete-correct](https://cloud.githubusercontent.com/assets/337677/14755124/9f5066e4-08e8-11e6-9c57-79fc4f93b92a.png)

2. Inside of brackets autocompletion fails:
![autocomplete-fails](https://cloud.githubusercontent.com/assets/337677/14755123/9f4cfed2-08e8-11e6-9758-3daae95411bd.png)

**Comment by VISTALL** [comment]
O_o. Repeated. Thanks. Please use next C# repository for C# bugs

**Comment by VISTALL** [comment]
Fixed. Please update C# plugin after 1 hour

**Comment by VISTALL** [comment]
Oh. i paused build server yesterday. I unpaused it. Today you can update plugins

**Comment by theshock** [comment]
Great! That was really fast, thank you
