### ISSUE TITLE
cannot recognize nest namespaces

### ISSUE THREAD

**Issue by jsuisen** [consulo/consulo#187]
![image](https://cloud.githubusercontent.com/assets/4002023/15132078/7aee95ca-1688-11e6-9c1a-e5634449d47e.png)

![image](https://cloud.githubusercontent.com/assets/4002023/15132081/836ae6fe-1688-11e6-9349-6813bbe77ef7.png)

**Comment by VISTALL** [comment]
Hi. I will check today

**Comment by VISTALL** [comment]
Fixed. You can update C# plugin after one hour.

And new C# issues please report it here https://github.com/consulo/consulo-csharp

**Comment by jsuisen** [comment]
thx :)
