### ISSUE TITLE
Cannot get interface method implementations(overrides) and usages.

### ISSUE THREAD

**Issue by vlasas** [consulo/consulo#189]
Cannot jump into A::method from IA::method. Put cursor on IA::method, then:
 - "Ctrl+Alt+B Implementations" - notifies "No implementations found"

Expected:  jump to A::method

Cannot find IA::method usage in C::call. Put cursor on IA::method, then:
 - "Alt+F7 Find Usages"  -  "No usages found in Project Files"

Expected:  jump to a.method() in C::call

```
    public interface IA {
        void method();
    }

    public class A : IA {
		public void method() {
		}
	}

    public class C {
		public void call() {
            var a = new A();
            a.method();
		}
	}
```
In Intellij IDEA pretty same code in Java we can jump from IA::method both:
  - "Ctrl+Alt+B Implementations" - reaching A::method implementation
  - "Alt+F7 Find Usages"  -  finding a.method() in C::call

**Comment by VISTALL** [comment]
C#? If yes - please report next issue here https://github.com/consulo/consulo-csharp

**Comment by VISTALL** [comment]
This feature is language specific

**Comment by VISTALL** [comment]
"Ctrl+Alt+B Implementations"  - implemented

**Comment by VISTALL** [comment]
Another part of this issue - have own issue at C# repo

https://github.com/consulo/consulo-csharp/issues/423
