### ISSUE TITLE
Getting these issues on build #1346

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo#193]
This these errors are popping up all the time on latest build:

![screen shot 2016-06-22 at 09 20 52](https://cloud.githubusercontent.com/assets/912814/16259872/9e362f7a-385c-11e6-8a10-9389f1e9e0f9.png)
![screen shot 2016-06-22 at 09 20 37](https://cloud.githubusercontent.com/assets/912814/16259884/a736eede-385c-11e6-85eb-84563c05a1a2.png)

**Comment by VISTALL** [comment]
Hi. What build you used? And can you attach idea.log file from here (https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

**Comment by sfjohansson** [comment]
Sure, here they are:

![screen shot 2016-06-22 at 09 37 51](https://cloud.githubusercontent.com/assets/912814/16260060/74af5266-385d-11e6-98e5-c69bcfbb17bc.png)

And the log
[idea.log.zip](https://github.com/consulo/consulo/files/327290/idea.log.zip)

**Comment by VISTALL** [comment]
Fixed. Update will be available soon. 

You have some exception (DisplaySortable) - please delete **napile** plugin

Ty

**Comment by sfjohansson** [comment]
will do...Awesome...faster than light as always! :)
