### ISSUE TITLE
Invalid system path

### ISSUE THREAD

**Issue by SillentAssembly** [consulo/consulo#194]
http://i.prntscr.com/2ad6a3e1dd764d99bef673a25f73db9b.png
- IDE build number: 1350
- Java version: 1.7.0_101
- OS name and version:  Linux Mint 17.3 Rosa

Happens randomly. I think when i double click error msg from unity to take me to consulo file/line but not sure.

Doesn't crash or anything. Once i lost git local history. Different msg tho. Dunno if related.

Sorry if i post on wrong place.

**Comment by VISTALL** [comment]
Np. Hm. Strange error. I will check it

**Comment by SillentAssembly** [comment]
I am able to reproduce this sometimes. It appears that this error(Invld sys path) comes up when i open an error msg from Unity console log(e.g unexpected symbol), and then when consulo opens the script in a new tab OR if tab is open but Analysis not finished, sometimes this error(Invld sys path) pops up. If a tab with that script is open on consulo AND analysis finished, everything is OK.
 It mostly happens if i spam(not 2-click but 3+ click) the error msg from Unity console log. Also sometimes even if Consulo is open Another instance starts if i 3+ click an error msg from Unity.

Hope this helps.

**Comment by SillentAssembly** [comment]
I think this happens when i multi(3+) click on Unity console log msg and Unity calls Consulo multiple times.

**Comment by VISTALL** [comment]
Ty for feedback

**Comment by VISTALL** [comment]
I think we can close this issue, due Consulo 2 is released. If repeated - create new issue
