### ISSUE TITLE
Parser/Linter shows incorrect error with method has infinite parameters (params keyword)

### ISSUE THREAD

**Issue by CasperPas** [consulo/consulo#196]
- IDE build number: 1350
 - Java version: 1.8.0_66
 - OS name and version: OSX 10.11.5 (15F34)
 - C# plugin version: 3226

Example/symptom: http://prntscr.com/bkfi73
Method's definition: http://prntscr.com/bkfi6y

**Comment by VISTALL** [comment]
Please report next issues(C#) here https://github.com/consulo/consulo-csharp

**Comment by VISTALL** [comment]
Looks like resolver found another method. I will check maybe after few days, for now busy with merge. Ty

**Comment by VISTALL** [comment]
Can't repeat. Can you try repeat it in simple case ?

**Comment by CasperPas** [comment]
I found that if we have "null" in the middle of those input parameters, it will cause the error. It won't happen if "null" is at the end:
```
public class TestScreenFxScene : MonoBehavior {
    void Start () {
        TestInfiniteParams("1st param", null, "3rd param", null);    // red underline on this line
        TestInfiniteParams("1st param", "2nd param", null);     // it's fine on this one
    }

    void TestInfiniteParams(params object[] items) {}
}
```

**Comment by VISTALL** [comment]
Thanks. Reproduced

**Comment by VISTALL** [comment]
Simplified

```csharp
public class Program
{
	void TestInfiniteParams(params object[] items)
	{
	}

	public static void Main()
	{
		TestInfiniteParams(null, null);
	}
}
```

**Comment by VISTALL** [comment]
Fixed. Thanks
