### ISSUE TITLE
Native file watcher is not executable

### ISSUE THREAD

**Issue by burakkurkcu** [consulo/consulo#201]
- IDE build number: 1355
- Java version: 1.8.0_51 x64
- OS name and version: OS X El Capitan 10.11.5

When I start Consulo it throws this in the event log:

"External file changes sync may be slow: Native file watcher is not executable: /Applications/Consulo.app/Contents/bin/fsnotifier"

I tried removing and reinstalling but no chance. It started with the new updates I think.

**Comment by VISTALL** [comment]
Hi. Its a bug with current distribution. I'ill fix it, when come home(in a
few days maybe). Sorry

**Comment by VISTALL** [comment]
Use chmod for set 755 access, sry

**Comment by VISTALL** [comment]
Fixed with last builds
