### ISSUE TITLE
Unity SDK 'Unity 5.3.5 (predefined)' is not defined"

### ISSUE THREAD

**Issue by VinditCo** [consulo/consulo#203]
Since the 5.4 update I'm getting :"Unity SDK 'Unity 5.3.5 (predefined)' is not defined" 

Tried clean install of Consulo with latest plugins. Any ideas on how to fix?

All the best

R

**Comment by VISTALL** [comment]
Since you change Unity, you need select another sdk in Project Structure

![](http://klikr.org/b44c787b7e3a9caae9ecc7010dd8.png)

(and reimport project)

**Comment by VinditCo** [comment]
Awesome, thank you !

**Comment by VISTALL** [comment]
np
