### ISSUE TITLE
Double clicking on error msg in unity does not take you to the corresponding file+line in consulo 

### ISSUE THREAD

**Issue by patrickoshaughnessey** [consulo/consulo#204]
- IDE build number: 1379
- Java version: 1.8_0_60
- OS name and version: Mac OSX El Capitan 10.11.6 

Issue description. In most cases need provide reproduce example.
1) Edit some code in Consulo to produce a compile error
2) Switch to Unity, and see the error in the console
3) Double click on the error
4) Notice that the line where the cursor ends up on does not correspond to the line of the error. In some instances, the proper file also does not open

**Comment by VISTALL** [comment]
You installed Consulo plugin for UnityEditor ?

**Comment by patrickoshaughnessey** [comment]
I did have it installed, but it looks like I had an older version (2615). I updated to 2662, but still see the same behavior. It opens up the right file, but the cursor goes to wherever the cursor was the last time the source file was opened.

**Comment by patrickoshaughnessey** [comment]
I updated all of the plugins within Consulo, and re-installed the Consulo plugin within Unity, and it seems to be better than it was -- it now opens to close to the right place in the code, but seems to always be 1 line off.

**Comment by VISTALL** [comment]
Can you show console log (one line), and show where cursor placed in Consulo

**Comment by VISTALL** [comment]
Moved to unity plugin 

https://github.com/consulo/consulo-unity3d/issues/84
