### ISSUE TITLE
Some classes aren´t recognized

### ISSUE THREAD

**Issue by diegogonzalez** [consulo/consulo#205]
- IDE build number:  1383
- Java version: 1.8.0_25
- OS name and version: OSx 10.11.6 

Some classes of the project aren´t recognized by some classes, but are recognized by others. Even the MonoBehaviour class MonoBehaviour. The ide say that de statement "using UnityEngine" isnt used. What other information can I contribute?

![captura de pantalla 2016-08-05 a las 2 46 59 p m](https://cloud.githubusercontent.com/assets/983846/17445488/9d91a05e-5b1b-11e6-9cce-7216da0b2fce.png)

**Comment by VISTALL** [comment]
Hi. You created project via 'Import Project' ?  Can you show Project Structure window at Unity3d extension (file -> project structure -> select root module -> extensions -> unity3d) 

![](http://klikr.org/bb56bac4ff2aa7a85bc635b6b717.png)

Thanks

**Comment by VISTALL** [comment]
Closed. If you repeated problem report 

https://github.com/consulo/consulo-csharp

or here

https://github.com/consulo/consulo-unity3d
