### ISSUE TITLE
Feature Request: braces around selection

### ISSUE THREAD

**Issue by ambs** [consulo/consulo#224]
Another interesting feature would be to surround  a selection with {}, () or [] accordingly with the character pressed. So, when there is a selection, and {,( or [ is pressed, instead of replacing the selection by the char, enclose the selection in {},() or [] respectively.

Best,

**Comment by VISTALL** [comment]
Hi. Currently i am working on 2.0(consulo 2.0) branch and can't time for this issue. I will back to this isse, when i open 2.0 beta download

Thanks

**Comment by ambs** [comment]
Sure. Let me know if you need beta testers, btw. I am loving to use Consulo!

**Comment by rogeratplumbee** [comment]
Same here. I have a full team working with it :)

**Comment by ambs** [comment]
Btw, this feature already exists. I found it later in the settings, so closing the issue :)
