### ISSUE TITLE
Consulo 1401 is totally broken on Unity5.5

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#225]
- IDE build number:
Consulo 1401 is totally broken on Unity5.5
- Java version:
- OS name and version: 
Mac OSX 11

Issue description. In most cases need provide reproduce example.
Parser compailer and update not working?

**Comment by VISTALL** [comment]
Can you show problem ?

**Comment by VISTALL** [comment]
I think you have fresh install Unity 5.5.

You need change SDK in Project Structure

**Comment by winalex** [comment]
<img width="1440" alt="screen shot 2016-09-20 at 6 14 37 pm" src="https://cloud.githubusercontent.com/assets/689092/18678989/288c0864-7f5e-11e6-9f89-3ae75dfa5e6c.png">

**Comment by VISTALL** [comment]
![](http://klikr.org/1fcb91d1c1977386f6589a81be23.png)


SDK(at right). Think you have like *Unity 5.4*

**Comment by winalex** [comment]
Ur right. Sorry. So Project is diff then modules???

**Comment by VISTALL** [comment]
It's idea names.

Project - is global thing. Modules - is child of it. (like Solutions and Projects in VS).

Problem fixed ?

**Comment by winalex** [comment]
YEAH. THX :*

**Comment by VISTALL** [comment]
Np
