### ISSUE TITLE
Huge error popover 

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo#227]
- IDE build number: See Image
- Java version:
- OS name and version: Mac OSX 11

Issue description. In most cases need provide reproduce example.
<img width="1440" alt="screen shot 2016-09-28 at 12 47 24 pm" src="https://cloud.githubusercontent.com/assets/689092/18910837/1221ba34-857a-11e6-802e-f26405671d8c.png">

**Comment by VISTALL** [comment]
Can you say parameters count ?

**Comment by winalex** [comment]
See the bottom of the screen to see how long it is. Don't know what u mean?

**Comment by VISTALL** [comment]
Oh. I see.

Thanks you
