### ISSUE TITLE
Compare changes

### ISSUE THREAD

**Issue by lowolf** [consulo/consulo#230]
When open history(file) panel key binding Ctrl+D(Win) or Cmd+D(osx) didn't work 
<img width="459" alt="screenshot 2016-10-04 20 35 32" src="https://cloud.githubusercontent.com/assets/931054/19078980/da9a8e84-8a73-11e6-9d43-217498ea814e.png">

**Comment by VISTALL** [comment]
Fixed in 2.0 version only
