### ISSUE TITLE
vim plugin press u "undo" not worked

### ISSUE THREAD

**Issue by NoviaDroid** [consulo/consulo#231]
- IDE build number: 1.0 #1401
- Java version: 1.8
- OS name and version: OSX 10.11 

when vim plugin is enabled, press u should work as command+z to execute undo operation, but failed.

It is very easy to reproduce.

**Comment by VISTALL** [comment]
Hi. Currently i am busy with next version of Consulo. Sorry.

Thanks

**Comment by VISTALL** [comment]
$moveto consulo-vim
