### ISSUE TITLE
Ошибка после добавления нового класса в проекте.

### ISSUE THREAD

**Issue by lowolf** [consulo/consulo#235]
- IDE build number: 1401
- Java version: 9
- OS name and version: osx Sierra

Проблема заключается в том, что после добавления класса, нет возможности его использовать т.к. IDE указывает, что класса не существует.

Помогает реимпорт проекта.

Такое же поведение при добавлении нового плагина.

**Comment by VISTALL** [comment]
Есть Re-Import Project, это действия можно найти в контекстном меню корневой директории.

Хорошего способа нету пока хендлить такое - нужно ручками вызывать

**Comment by lowolf** [comment]
Ну да, как вариант можно пока и так жить, либо повесить триггер на добавление классов в проект.

**Comment by VISTALL** [comment]
Задача такая есть. Но пока на неё нету времени

https://github.com/consulo/consulo-unity3d/issues/45

**Comment by lowolf** [comment]
Валерий, добрый день!


Когда выйдет Consulo 2.0? Очень хочется уже посмотреть :)


Best regards, Denis

**Comment by VISTALL** [comment]
Добрый день. Возможно в январе. Я выпал на один месяц (до сих пор - я почти не работаю по Consulo, ибо нахожусь не в СПб). 

Спасибо

**Comment by lowolf** [comment]
Понял, спасибо большое за ответ!


Best regards, Denis
