### ISSUE TITLE
Working on Consulo2

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#236]
I know ur busy and working on Consulo2. I've been working in many IDE from notepad (if can be considered IDE back in time and Consulo. 20 years and all IDE have moved from mechanic type machine to electronic type machine. Compared to computers 0.001% progress. With all shit like intellisense, finds, autogeneration ... we have in VS,IDEA and Consulo...just advance typing machine. YOU CAN"T SEE WHAT IS THE RESULT OF TYPING.
If you are smart you will take that pluggin(https://www.youtube.com/watch?v=qKjdKKZ1Sow) learn and make best editor 4 Unity. I could buy 4 u C#. What u see is what u code. You will be famous, rich what every you are up to. If I was so deep in IDE dev I would do it and jump before all stupid CEOs assholes in IntelliJ and MICROSOFT....than u can do same for IOS, ANDROID,....so on. Don't listen my bullshit keep making ur TextEditor2. 👍

**Comment by VISTALL** [comment]
You can always change IDE

**Comment by winalex** [comment]
Intention was to trigger something good and advanced, not offend u or ur work. But Nah. I can't blame u for shortsightedness, cos you at least don't have budget like Microsoft or IntellJ, Sun, Google, Apple.. https://vimeo.com/36579366

**Comment by VISTALL** [comment]
I have no idea - how integrate code highlight into Unity (and decompiler is not good idea at all). 

Lose 6 month or more - for single unity integration, it's a bad spent time.

Anybody can learn Unity API, and show me example (like this guy https://github.com/consulo/UnityEditorConsuloPlugin/pull/5)

**Comment by winalex** [comment]
You don't need to integrate editor inside Unity ide, as Livity does. You need to communicate from Consulo just as you/anyone did with UnityEditorConsuloPlugin, but not just to jump on line of error, but on bigger scale. You can decompile Livity.dlls its totaly legal when its purchased.

**Comment by VISTALL** [comment]
>> You need to communicate from Consulo just as you/anyone did with UnityEditorConsuloPlugin, but not just to jump on line of error, but on bigger scale

I am not Unity coder. I don't known that they(unity users) need. Anybody can create issue/feature and discuss with me about it.

Nobody paid me for Unity integration (or etc).  Consulo is my primary IDE  for Java/C# languages (and that why i develops it). There no goal create the best Unity IDE (not from my side).

**Comment by winalex** [comment]
OK. Language doesn't matter. Nether you need to create new Unity. We need coding editor that will show what we are doing. But its not about Unity C# or any....For example I'm coding Form in Java. How can I say the changes on my form without wait to recompile run every time. So what will IDE help me??? No to add syntax error??? It is 2016-7 its not 1980. C-64. Go watch Bred video one more time. If u don't get its OK. NP.
