### ISSUE TITLE
Commenting at first line

### ISSUE THREAD

**Issue by burakkurkcu** [consulo/consulo#243]
- IDE build number: 1401
- Java version: 1.8.0_76 release (integrated)
- OS name and version:  Mac OSX Sierra 10.12.1 (16B2555)

<img width="525" alt="bug-report" src="https://cloud.githubusercontent.com/assets/5931039/20503536/9d98b512-b04b-11e6-8eb7-ae75f637e0bd.png">

**Comment by VISTALL** [comment]
This option is lang specific, and require own impl for each language. I will check it - after maybe in december (no access to my pc).

Thanks

**Comment by burakkurkcu** [comment]
Yes, it is base feature needed in all supported languages. Not an urgent or big deal but a little annoying :)

**Comment by VISTALL** [comment]
fixed in second version
