### ISSUE TITLE
Cannot find declaration when new line symbols are mixed

### ISSUE THREAD

**Issue by bartekczyz** [consulo/consulo#245]
I have some problems with scripts that were created in Unity on Windows. I can open them, but IDE seems to have problems resolving symbols. Even converting lines doesn't help. It also applies to libraries with mixed new line symbols. Previous versions of Consulo also had this bug.

- IDE build number: 1401
- Java version: 1.8.0_76
- OS name and version: OS X 10.11.6

**Comment by VISTALL** [comment]
You need call - 'Re-Import Unity Project' action in context menu on root project dir.

**Comment by bartekczyz** [comment]
It worked! :D Thanks Valeriy!

**Comment by VISTALL** [comment]
It's known issue https://github.com/consulo/consulo-unity3d/issues/45
