### ISSUE TITLE
SVN is missing

### ISSUE THREAD

**Issue by bartekczyz** [consulo/consulo#247]
I've just installed Consulo 2 and it seems like it doesn't support Subversion. I also wasn't able to find it in plugins. Any ideas?

- IDE build number: 2.0 #1556
- Java version: 1.8.0_76
- OS name and version: OS X 10.11.6

**Comment by VISTALL** [comment]
Hi. Subversion plugin is not moved to Consulo due no users. As i understand you need it, I will check it.

**Comment by bartekczyz** [comment]
Hi Valeriy,
unfortunately we still use svn. It would be awesome if you include SVN support in next build. Thanks for your great work! ;)

**Comment by VISTALL** [comment]
Can you switch to beta channel? (Preferences -> General -> Platform & Plugins & Web services) And call About -> Check for updates?

And then install SVN plugin after update

**Comment by bartekczyz** [comment]
Yikes, After updating to beta I can't run Consulo any more:

2017-01-18 15:34:20.179 consulo[8337:969954] Cannot load JVM bundle: Error Domain=NSCocoaErrorDomain Code=3587

**Comment by VISTALL** [comment]
Hm!
Try to download it via this link https://hub.consulo.io/api/repository/download?channel=beta&platformVersion=1571&pluginId=consulo-mac64&version=1571&platformBuildSelect=true

**Comment by bartekczyz** [comment]
Thanks a lot, it works now :)

**Comment by VISTALL** [comment]
I created new issue with update bug(looks like specific only on mac, and bug is not stable)

https://github.com/consulo/consulo/issues/248
