### ISSUE TITLE
Legacy consulo plugins can crash unity

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo#250]
I had an issue with a lot of random unity editor crashes...in the end I managed to track it down to be different version of the consulo .dlls in the project.

Maybe have the new fancy plugin updater hunt down possible old versions, as users might run into a lot of headache if this happens.

**Comment by VISTALL** [comment]
Hi. It already implemented. Maybe old library was inside another directory ? (not in default, as in readme)

**Comment by sfjohansson** [comment]
let me see....they were in Editor/Plugins/

**Comment by VISTALL** [comment]
Can say old and new plugin paths (if you not forgot it)

**Comment by sfjohansson** [comment]
the names where xxx4.6  xxx5, assuming that 5.3 is latest

**Comment by VISTALL** [comment]
okey i will try reproduce maybe at this week.

Thanks

**Comment by sfjohansson** [comment]
cheers :)

**Comment by sfjohansson** [comment]
btw not related to to this issue...the fonts are garbled/weird smoothed in latest on windows (used v1 before)?

**Comment by VISTALL** [comment]
Try drop bundled JRE from Consulo (Consulo/platform/buildNUMBER/jre), and use Oracle JDK 1.8

**Comment by sfjohansson** [comment]
so use the advanced build that is without and then install JDK 1.8?

**Comment by VISTALL** [comment]
yeah. I will update bundled jre builds, when i get mac device (maybe at with week too)

**Comment by sfjohansson** [comment]
Cool...well I give the unbundled a go :)

**Comment by VISTALL** [comment]
Changed notification. Now it will delete all old plugins from file system

![](http://klikr.org/c81821a92ad63055bf1464fd913d.png)
