### ISSUE TITLE
How can install plugins not option

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#253]
- IDE build number:
2.0
- Java version:
- OS name and version: 
MAC 

Issue description. In most cases need provide reproduce example.

**Comment by VISTALL** [comment]
what? i am not understand you

**Comment by winalex** [comment]
Preferences>General>Platform and Pluggins   where is option in entry screen???

**Comment by VISTALL** [comment]
It's here

![](http://klikr.org/0a5033c33a79230dd6b44a9cb42d.png)

Or on top menu: Consulo -> Preferences (at mac)

**Comment by winalex** [comment]
Same. You need to go to Preferences>General>Platform and Plugins. In previous version there was Pluggins direct link cos is used often

**Comment by VISTALL** [comment]
Why you use so often?

**Comment by winalex** [comment]
You are the boss

**Comment by VISTALL** [comment]
It's question for usability. I working on Consulo - where plugins not conflict with each other. If you disable - enable some plugin on start - its a bad case (and need change it).

**Comment by SillentAssembly** [comment]
In version 1556, ctrl + shift + a ---> type "plug" ---> no plugins option reference.

In v.1401 below is OK.
http://prnt.sc/ee6b4a

notice the second option is missing from v.1556 below
http://prnt.sc/ee6asr

**Comment by VISTALL** [comment]
This action was dropped from welcome frame. Looks like it was only one action for access to plugins via action. I will return it (not to welcome frame - i am not hear why you access too often)
