### ISSUE TITLE
Have issues with Linq and generics

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#254]
<img width="1440" alt="screen shot 2017-03-08 at 1 14 38 pm" src="https://cloud.githubusercontent.com/assets/689092/23742073/c23306b6-04ab-11e7-8eeb-28b9fdace9f9.png">
<img width="1440" alt="screen shot 2017-03-08 at 1 14 16 pm" src="https://cloud.githubusercontent.com/assets/689092/23742074/c3d1b2b0-04ab-11e7-8984-197e0697d0a7.png">
<img width="1440" alt="screen shot 2017-03-08 at 1 14 08 pm" src="https://cloud.githubusercontent.com/assets/689092/23742081/c927ff58-04ab-11e7-9b24-d983e90c2980.png">

- IDE build number: latest
- Java version:
- OS name and version: Mac OSx ElCaptain

Issue description. In most cases need provide reproduce example.

**Comment by VISTALL** [comment]
moved https://github.com/consulo/consulo-csharp/issues/462
