### ISSUE TITLE
Find Occurences output is empty in Find tab

### ISSUE THREAD

**Issue by patrickoshaughnessey** [consulo/consulo#257]
# Please read contributing guide first. Please read and remove this header before issue submit

- IDE build number: 1641
- Java version: 1.8.0_102
- OS name and version: MacOS Sierra 10.12.4

Issue description. In most cases need provide reproduce example.
Every time I search using "find in path", the results are showing blank in the Find tab. This does not happen for other types of search, such as "Find Usages", etc.

The results show up fine in the preview tab of the find dialog, but after choosing "Find", the Find output is always blank.

Screenshots below:
![findinpathinput](https://cloud.githubusercontent.com/assets/115180/25018530/19078a5e-204d-11e7-8e1d-0075f707a48d.png)
![findinpathpreview](https://cloud.githubusercontent.com/assets/115180/25018533/1ce0c8b6-204d-11e7-8d31-6fbe76c0a190.png)
![findinpathoutput](https://cloud.githubusercontent.com/assets/115180/25018537/1eed8e28-204d-11e7-88bf-ce798ea3f87d.png)

**Comment by VISTALL** [comment]
Hi. Tested and fixed
