### ISSUE TITLE
No delete action at welcome screen, when project name is too long

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo#260]
![](https://cloud.githubusercontent.com/assets/689092/25200752/be08c3e0-254f-11e7-80c1-6ef203b12a24.png)

From https://github.com/consulo/consulo-unity3d/issues/101#issuecomment-295422162

**Comment by winalex** [comment]
Think the problem arise not cos of long title, cos short title doesn't have "X" also, but try to delete .consulo dirs...

**Comment by VISTALL** [comment]
It was bug with long project name. You can see X - when scroll to right.
