### ISSUE TITLE
New Version is totally broken

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#264]
- IDE build number:
- Java version:
- OS name and version: 

Issue description. In most cases need provide reproduce example.

## If you can't determine with issue - use our forum (https://discuss.consulo.io/)

**Comment by VISTALL** [comment]
Hi. It contains new fix for update. Re-download is required. Sorry.

**Comment by winalex** [comment]
First was requesting pluggings update and then can't start.

**Comment by VISTALL** [comment]
Yeh - crashed. I think it's last problem with auto-update on macOS. I am trying to stabilize auto-update on macOS (in prev issue I wrote it)

**Comment by winalex** [comment]
what should I do. Night build?

**Comment by VISTALL** [comment]
One moment.

**Comment by VISTALL** [comment]
Need sometime when all builds pushed to release channel. I will write when it's done. Around ten minutes

**Comment by VISTALL** [comment]
It's finished. Please download Consulo build 1667. Tested it works. It not create post on https://discuss.consulo.io (not spam issue tracker)
