### ISSUE TITLE
Some text output doesn't support Windows desktop scaling

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#274]
- IDE build number: 1696
- Java version: 1.8
- OS name and version: Win10

In Windows if display scaling is enabled, some elements of Consulo display unzoomed text. For example, tip of the day (scale is 200%):
![startup_tips_vs_win_scale_200](https://cloud.githubusercontent.com/assets/16825982/26400260/d841c7da-4088-11e7-9a24-bda2b8ee200c.png)
(also note picture is broken)

Plugin description and vendor have same problems (scale is 200%):
![plugin_desc_and_vendor_vs_win_scale_200](https://cloud.githubusercontent.com/assets/16825982/26400270/e15e5b26-4088-11e7-8505-5cb877138a36.png)

**Comment by VISTALL** [comment]
Hi. Thanks for issue. I saw it on my notebook, but forgot.

About tips of the day, it's so outdated - maybe i disable it.
