### ISSUE TITLE
Pixel-perfect icon for Consulo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#277]
- IDE build number: 1696
- Java version: 1.8.0_112
- OS name and version: Win10

Consulo icon is assumed to be a black 5x5 pixel square С surrounded by single grey pixel (so 7x7 pixels in total). After scaling 7x7 into 16x16 (as well as 32x32, 48x48, 64x64) scaling artifacts appear so icon looks dirty:
![consulo_icon_old](https://user-images.githubusercontent.com/16825982/26855488-ea714660-4b23-11e7-86c6-871243a80cfd.png)

I propose scaling 7x7 into 14x14 (with 2 excess transparent pixels for 16x16). Icon would be a bit smaller but pixel-perfect:
![consulo_icon_new](https://user-images.githubusercontent.com/16825982/26855534-2980cf74-4b24-11e7-9328-a40f587ae764.png)

Resulting .ico file:
[consulo_icon.zip](https://github.com/consulo/consulo/files/1056530/consulo_icon.zip)

**Comment by VISTALL** [comment]
Hi. Can you attach png files too? (16x16 - 32x32 (and with white "C" - it's used when consulo in sandbox mode)

I will try to replace all icons - and check how it looks like

Thanks

**Comment by unv-unv** [comment]
PNG files:

16x16:
![consulo_icon_16x16](https://user-images.githubusercontent.com/16825982/26856539-eabceb52-4b2c-11e7-8003-7a32c5e7df18.png)

32x32:
![consulo_icon_32x32](https://user-images.githubusercontent.com/16825982/26856540-eabf0108-4b2c-11e7-8989-13e2eabad813.png)

48x48:
![consulo_icon_48x48](https://user-images.githubusercontent.com/16825982/26856541-eac0c45c-4b2c-11e7-8fc8-a05dc694c344.png)

64x64:
![consulo_icon_64x64](https://user-images.githubusercontent.com/16825982/26856542-eac64440-4b2c-11e7-94bc-67e8fb99d8d7.png)

**Comment by unv-unv** [comment]
With white C:

16x16:
![consulo_icon_whitec_16x16](https://user-images.githubusercontent.com/16825982/26856642-a32cfff6-4b2d-11e7-9d33-d4c3e2d72a22.png)

32x32:
![consulo_icon_whitec_32x32](https://user-images.githubusercontent.com/16825982/26856640-a32a2290-4b2d-11e7-84ee-26022083e82e.png)

48x48:
![consulo_icon_whitec_48x48](https://user-images.githubusercontent.com/16825982/26856643-a3301254-4b2d-11e7-89c8-2d6b0a1bcbf2.png)

64x64:
![consulo_icon_whitec_64x64](https://user-images.githubusercontent.com/16825982/26856641-a32b7bf4-4b2d-11e7-9220-39a615f82248.png)

**Comment by VISTALL** [comment]
Hi. I pushed changes to Nightly channel. At this week I will decide - leave it, or revert.

Exe files will not updated on update(it's boot part, not updatable for now).

You can switch to Nightly channel, update exe files (from this https://github.com/consulo/consulo/tree/master/distribution/boot/win) - and try

**Comment by VISTALL** [comment]
I leave them.

Thanks
