### ISSUE TITLE
IDE Download doesn't work

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#278]
- IDE build number: 1696
- Java version: 1.8.0_112
- OS name and version: Win10

Getting error while trying to download any build from official download page (https://github.com/consulo/consulo/wiki/Downloads):

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Jun 07 00:03:08 UTC 2017
There was an unexpected error (type=Internal Server Error, status=500).
No message available
```

**Comment by VISTALL** [comment]
In Progress

**Comment by VISTALL** [comment]
fixed.

Thanks
