### ISSUE TITLE
Pictures in Tip of the day should support Windows desktop scaling

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#279]
- IDE build number: 1742
- Java version: 1.8.0_112
- OS name and version: Win10

Next incarnation of issue #274. Text in tips of the day does now correctly support scaling and even pictures are correctly shown now - thanks. Though pictures need to be scaled as well (in the following example scaling is 200%):
![startup_tips_pictures_vs_win_scale_200](https://user-images.githubusercontent.com/16825982/26876644-d7fb7cc8-4b8f-11e7-881f-507361d17aa6.png)

**Comment by VISTALL** [comment]
fixed. But idk when images will be updated. There no time for this minor change.
