### ISSUE TITLE
Artifacts in Inspection Profile dialog

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#283]
- IDE build number: 1777
- Java version: 1.8
- OS name and version: Win10

Inspection Profile dialog (Analyze > Inspect code > Inspection profile > ...) produces visual artifacts while focusing rows one by one (either by mouse or keyboard):
![artifacts_in_inspection_profile_dialog](https://user-images.githubusercontent.com/16825982/27315002-d57bc58a-557f-11e7-88f4-f55bd3cd6384.png)

Also shouldn't it have name in its caption? Like "Inspection Profile" or similar?

**Comment by VISTALL** [comment]
Hi.

Yeah. Need title.

Will check after java merge(plus after jsp error fix)

Thanks

**Comment by unv-unv** [comment]
Checked after last update. Visual artifacts fixed. But window still needs caption.

**Comment by VISTALL** [comment]
Can you say steps - how you show dialog of inspections?

**Comment by unv-unv** [comment]
Analyze > Inspect code > Inspection profile > ...

**Comment by VISTALL** [comment]
fixed
