### ISSUE TITLE
Do you have plans for SQL plugin?

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#284]
Plugin for .sql files.

**Comment by VISTALL** [comment]
Yeah. Consulo had some plugin for SQL (https://plugins.jetbrains.com/plugin/1800-database-navigator).

But i had disabled it due perfomance problem (very long delay on start by **wrong idea** of sql parsing by plugin author) - and without rewrite, i can't push it to repository

Thanks

**Comment by unv-unv** [comment]
From its name i imagine... Does it parse whole database structure on IDE start? :)

Speaking about which SQL plugin is more relevant, from my point of view it's more important for IDE to be able to highlight SQL in string constants of general languages. There're many tools for syntax highlighting of plain SQL and many tools for SQL execution. Of course, it would be tempting to have SQL IDE which is able to perform refactorings not only within single query, but analyzing whole structure of tables, views and procedures, though it's so complex to make and mantain (remember number of databases with different SQL dialects) so I don't think this deserves efforts.

**Comment by VISTALL** [comment]
No. It's analog SQL plugin from IDEA (it was created before JB plugin)

Author declarate SQL languages in XML files (each tokens, etc), each file contains around 2k lines.

On start he read this files (and process it with very deep registration). It's eat time and CPU at start.

Idk how fix it for now. Need rewrite lexer&parsing for that - for now i don't known when

**Comment by VISTALL** [comment]
For example. Oracle SQL xml file is 8k lines

https://github.com/consulo-trash/consulo-sql/blob/master/resources/com/dci/intellij/dbn/language/sql/dialect/oracle/oracle_sql_parser_elements.xml

MySQL (1.6)

https://github.com/consulo-trash/consulo-sql/blob/master/resources/com/dci/intellij/dbn/language/sql/dialect/mysql/mysql_sql_parser_elements.xml

**Comment by VISTALL** [comment]
I will restore my old plugin, but idk his fate

**Comment by VISTALL** [comment]
Maybe

**Comment by VISTALL** [comment]
Started but with low priority. At start will be only db viewer, later sql, etc.

https://github.com/consulo/incubating-consulo-database
