### ISSUE TITLE
Extract method signature preview doesn't support win scaling

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#285]
- IDE build number: 1780
- Java version: 1.8
- OS name and version: Win10

Extract method refactoring window has "Signature Preview" frame which currently doesn't support desktop scaling (example with 200% scaling):
![extract_method_vs_win_scale_200](https://user-images.githubusercontent.com/16825982/27422462-ec7d52fe-5736-11e7-9169-5cdd1319a7e3.png)

I'm not sure whether it's a Platform issue or Java plugin issue.

**Comment by unv-unv** [comment]
Nothing changed after last update in nightly.

**Comment by VISTALL** [comment]
Jenkins handle commits with some delay (few hours), due limitation of CI server

![](http://klikr.org/31e0e4f7231ea6fbaabd8971b576.png)

(there no build for last commit)

**Comment by unv-unv** [comment]
Understood.

**Comment by unv-unv** [comment]
Updated after several hours - fixed. Thanks.
