### ISSUE TITLE
Desktop scaling support in Editor settings

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#287]
- IDE build number: 1784
- Java version: 1.8
- OS name and version: Win10

The following controls don't support desktop scaling in Settings:
* Editor / Code Completion / Postfix Completion / Before+After
* Editor / Code Intentions / Description+Before+After
* Editor / Colors&Fonts / General / Example (bottom pane with example text)
* Editor / Colors&Fonts / Console Colors / Example
* Editor / Colors&Fonts / Console Font / Example
* Editor / Colors&Fonts / Font / Example
* Editor / Colors&Fonts / Language Defaults / Example
* Editor / Colors&Fonts / (Custom|HTML|Java|Manifest & Bnd|Properties|XML) / Example
* Editor / Copyright / Formatting / Example
* Editor / Copyright / Formatting / (DTD|HTML|JAVA|Properties|XHTML|XML)/ Example
* Editor / File and Code Templates / Description

Maybe it requires only single fix of textarea-like control but just in case I've listed all the locations I had found. My plugins are: Java, Java Bytecode Decompiler, JavaEE, Properties Support, Subversion Integration, XML.

**Comment by VISTALL** [comment]
gm. oh so many problems. I had hidpi notebook but not often use it - and not saw them. In progress.

Thanks

**Comment by VISTALL** [comment]
and you was right it was bug almost in one place

**Comment by unv-unv** [comment]
Checked after last update - almost all places are fixed. Except for Copyright section. It seems to use another textarea-like control without line numbers. So there's still a need to fix following places:
* Editor / Copyright / Formatting
* Editor / Copyright / Formatting / (DTD|HTML|JAVA|Properties|XHTML|XML)

**Comment by VISTALL** [comment]
Fixed. Changed code to more clear view. Next time - please create new issues, for better tracking

Thanks

**Comment by unv-unv** [comment]
Checked all the aforementioned places after the last update - now fixed. Thanks.

Didn't create new issue because unfixed places were mentioned in initial bugreport.

**Comment by VISTALL** [comment]
my bad. I messed

**Comment by unv-unv** [comment]
:)
