### ISSUE TITLE
Cannot Run as Administrator consulo64.exe

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#291]
- IDE build number: 1790
- Java version: 1.8
- OS name and version: Win10

Trying to Run as Administrator C:\Program Files\Consulo\consulo64.exe. Getting the following error:
![platform_directory_not_found](https://user-images.githubusercontent.com/16825982/27512264-bb208dd4-5943-11e7-8781-659550e8504c.png)

Running normally works OK.

**Comment by VISTALL** [comment]
Hm. Strange error.

**Comment by VISTALL** [comment]
fixed in master - but not pushed to platform repository. Maybe at this week i will push it
