### ISSUE TITLE
Single search result is hidden by scroll bar

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#293]
- IDE build number: 1805
- Java version: 1.8
- OS name and version: Win10

Press Ctrl+N or Ctrl+Shift+N, narrow search results to single one - and horizontal scroll bar would make it not visible:
![single_search_result_hidden_by_scroll_bar](https://user-images.githubusercontent.com/16825982/28578136-742d0df4-7161-11e7-8fdf-784493f0639a.png)

**Comment by VISTALL** [comment]
Hi. Hm.

**Comment by VISTALL** [comment]
Can't reproduce. I think it's duplication of another scrollbar issue (already fixed)

Thanks

**Comment by unv-unv** [comment]
Checked in 1808 - still present (ensure search result is longer than input width):
![single_search_result_hidden_by_scroll_bar_2](https://user-images.githubusercontent.com/16825982/29109477-d00e7708-7ceb-11e7-948e-e798f0299ed2.png)

**Comment by VISTALL** [comment]
Hmm, HiDPI?

**Comment by unv-unv** [comment]
Yes, 200%.
