### ISSUE TITLE
Delete change list not work

### ISSUE THREAD

**Issue by lowolf** [consulo/consulo#294]
- IDE build number: 1808
- Java version: 1.8.0_152
- OS name and version: osx 10.12.6

If you try delete change list it will be not work

<img width="281" alt="screenshot 2017-08-14 10 53 58" src="https://user-images.githubusercontent.com/931054/29258875-51475faa-80df-11e7-9c8e-12a41c70d87a.png">

**Comment by VISTALL** [comment]
Hi. Hmm

Thanks, will check in the evening

**Comment by VISTALL** [comment]
My bad i missed some code from Kotlin

https://github.com/consulo/consulo/blob/master/modules/vcs-impl/src/com/intellij/openapi/vcs/changes/actions/ChangeListRemoveConfirmation.java#L33

Bad TODO.

Will fix in few days.

Sorry and thanks for remember about it
