### ISSUE TITLE
Lost shelf data

### ISSUE THREAD

**Issue by pecheny** [consulo/consulo#296]
- IDE build number: 1817
- Java version: 1.8.0_152
- OS name and version: win 10 pro

1. VCS panel, select some  files and choose 'shelve' in the context menu, shelf tab appears and all seems fine
2. When consulo loose focus it shows error:
![Error](https://image.prntscr.com/image/EBYX9860TVuKtZ13T7xcvg.jpeg)
Cannot save scheme %Shelf_name%
3. If you close consulo now, all shelved data will be lost.

**Comment by VISTALL** [comment]
Hi

Can you attach log file? (consulo.log - About -> Show log in explorer)

Thanks

**Comment by pecheny** [comment]
Here it is
https://gist.github.com/pecheny/f87c75cd29369f23e1a349ef0dfc1a7b

**Comment by VISTALL** [comment]
Strange there no exception. Can you attach old logs (with extension .1 .2 .3 etc)

**Comment by pecheny** [comment]
Reproduced several times after erasing logs on several new empty projects.
https://gist.github.com/pecheny/be651c3e0d82e464956d74f34e3b66ca

**Comment by VISTALL** [comment]
Thanks, now it's more understandable

**Comment by VISTALL** [comment]
Hi. I'm added check (and debug) must be better after 1853 build. Notify me after this build

Thanks

**Comment by pecheny** [comment]
I'd tried to update Consulo and have found that there is no compatible Unity3D plugin for now, so i had to rollback old build.

**Comment by VISTALL** [comment]
Hi. Sorry. I forced channel iteration. It's known bug https://github.com/consulo/hub.consulo.io/issues/19

Thanks for notify
