### ISSUE TITLE
Menu item Help / Edit Custom VM Options doesn't exist

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#304]
- IDE build number: 1874
- Java version: 1.8
- OS name and version: Win10

Latest build suggests increasing code cache size via menu item Help > Edit Custom VM Options which doesn't exists:

![code_cache_size_misplace](https://user-images.githubusercontent.com/16825982/31613721-99ca8728-b28c-11e7-948d-8a612839417d.png)

**Comment by VISTALL** [comment]
You can change vm option file by hands (it's placed around exe file)

**Comment by VISTALL** [comment]
changed text. Now it send to https://github.com/consulo/consulo/wiki/VM-Options
