### ISSUE TITLE
Update checker should warn if not all installed plugins are updated

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#310]
- IDE build number: 1905
- Java version: 1.8
- OS name and version: Win10

Since plugins build is asynchronous, there're a lot of situations when you run update checker and it shows that a lot of plugins are updated. Then it downloads these plugins, restarts IDE - and I see error that some of the plugins aren't loaded. They're uncompatible with recent version because their most recent update was not available at the time I pressed "Help > Check for Update...". And IDE becomes unusable.

Update checker should warn me if latest updates aren't available for all of the installed plugins. It shouldn't force me to check number of updated plugins visually just to prevent IDE become unusable.

**Comment by VISTALL** [comment]
Hi. That good idea.

And now me interest - why Java plugin is broken. Few mins i will fix it. Sorry

Thanks

**Comment by VISTALL** [comment]
Fixed Java java (few mins ). I think need some notification about this. Maybe telegram bot.
Thanks

**Comment by VISTALL** [comment]
And some situation. For example I delete plugin from repository - on update it will warn about this plugin (no updates for it). 

Most users will not accept update, they will think - it's an error. 

In close future - i will remove **IntelliLang** lang plugin (merge into platform), but some users will get error on update. >.<

**Comment by unv-unv** [comment]
Java is working - thanks!

**Comment by unv-unv** [comment]
If you remove IntelliLang plugin from repository, you'll still need to remove it somehow from user installation. For example, by making the last version of plugin as uninstaller for the plugin. So update for the plugin would still be available.

**Comment by unv-unv** [comment]
After last nightly update (update checker said updates were built 7 hours ago) IDE became unusable again:
```
15.01.2018
8:37	Plugin Manager: Following plugins are incompatible with current IDE build: JavaScript, Java, JavaEE, Java Bytecode Decompiler (Via Fernflower)
```

Java plugin version: 2202
IDE version: 1932

**Comment by VISTALL** [comment]
Hi. Yeah, i known, i broke some logic in platform, will fix today. Sorry (it's only nightly channel)

**Comment by VISTALL** [comment]
almost all fixed

**Comment by VISTALL** [comment]
fixed, sorry

**Comment by unv-unv** [comment]
Thanks, working again.

Please note that there's still no way to downgrade by selecting another channel in settings.

**Comment by VISTALL** [comment]
Yeah, that not fixed. Not easy to fix. And i'm busy on primary work, they gave me too many tasks after NY

**Comment by VISTALL** [comment]
fixed
