### ISSUE TITLE
You need ultra fast computer for using consulo

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo#315]
Test machine: Dual core T7500 2.2GH 4GB RAM

Every run is indexing files having 100% CPU.
![clipboard02](https://user-images.githubusercontent.com/689092/33990098-1f5b0a28-e0ca-11e7-9868-38946c4f3e0e.jpg)

If I just click on the line in Editor goes 40-50% CPU
![clipboard01](https://user-images.githubusercontent.com/689092/33990162-514898b6-e0ca-11e7-98d1-ffaa87712c59.jpg)

Parsing 1file of 1000 lines c# took lot of time. It really crazy, that I can even see progress bar checking syntax. 2 processors can't process 1000 lines in one micro seconds.... My gradma know how to build app that works only od Octa cores just to write formatted text. :1st_place_medal:  :)

Overrall not optimized.

**Comment by VISTALL** [comment]
Hello.

About indexing. It's normal because Consulo analyze all sources & libraries in project (including dll from Unity, or meta files).

About source viewing & editing. It's not normal. Pure computers more sensitive to optimization problems (there no ideal implementation of language). In this case need option to reproduce. There 100% it's not reproduced on simple C# console project.

I don't have so pure test machine.

> My gradma know how to build app that works only od Octa cores just to write formatted text.

nah. It's not only formatted text. You can disable some of features here

![](http://klikr.org/49b4991b467525c9fcfd57dd1611.png)

And enable **Power Save Mode**, and you will get almost default **notepad**

I'm always open for pull requests. You can invite your grandma - if she so powerfull. 

My granny can only burn wood for warm in -35 °C (and it's not joke)

**Comment by VISTALL** [comment]
PS: Windows XP is not supported by Microsoft or Oracle (jdk builds). Newest builds of JDK even can't start on it.

**Comment by winalex** [comment]
I'm on Win7 64bits and can click on any folder it opens where fast.
1. Why your grandma need to count wood every time she wants to run fire. Every start LogicForge is indexing. Count if Win index with every run same folder and even not changed same folder with every start. Nonsense.
![image](https://user-images.githubusercontent.com/689092/34210980-fe74c4ac-e597-11e7-847d-904b4f82ef64.png)

2. She don't need to index .meta, show in search or anything. They are internal Unity files and when I program C# I wan't to see only C#. When I hit file or class search don't wan't to see .meta at all.
3. I'm seeing indexing while I"m working. I'm 100% I didn't add any new .cs file or any file at all to wait reindexing.... which hangs whole computer.
4. Why you grandma would like fireplace without fire. (why i would use consulo(req 2GB) if have same functionality as notepad in PowerSave mode. But you grandma need fire in the fireplace not fire to burn the house. I have one file opened about 1000 lines and 
![image](https://user-images.githubusercontent.com/689092/34210824-73a50152-e597-11e7-8e61-bd62a060273e.png)
wait 5-8sec. to see popup. 
![image](https://user-images.githubusercontent.com/689092/34210965-eadec7f8-e597-11e7-9d9e-49c2e71efa82.png)
See you print screen you have 1.2GB reserved and you don't have even one file in the empty project.

**Comment by winalex** [comment]
I'll install VisualStudio Comunity edition and compare speed and 
or IntellJ I would prove you need to work on optimization u lazy ass :)

**Comment by VISTALL** [comment]
About meta files.

Consulo indexing it for creating key-value File=GUID. It's need for showing linemarkers inside C# code.

For example - this C# class using in Unity scene. Or this field is initialized in Unity scene

![](http://klikr.org/496abaab373bffc3eb4fb72e3a28.png)

Also it's need for correct field renaming which replace references in unity assets (not provide unknown field name in it, after rename in C# file)

**Comment by VISTALL** [comment]
About indexing on start.

Consulo fully indexed source only once per project. On **cold** start, only cache validation start.

If you got infinity indexing on restart, it's a bug - which need to fix. Please attach log

**Comment by VISTALL** [comment]
About slow completion. 

As i said 
>  Pure computers more sensitive to optimization problems (there no ideal implementation of language)

If you think, logic for show completion is so easy - you are wrong.

It's not show all members of target type (only accessable), also it's show **extension** members which can be placed in **any** used namespace(which need analyze too), and need analyze target type for extension, or you will see **ALL** extensions in completion.

Also, completion sorted - which type is expected, and up better variants.

Also, obsolete variants go down, prefer **good*** variants.

Also, its show non-imported elements, which will be imported after pressing enter.

Also...

I need to continue? If you do not see something that does not mean that it does not exist.

**Comment by VISTALL** [comment]
About laziness.

You are right. Me lazy (not joke). It's my sin. 

After all, I am working on my primary job at weekdays, and when i get free time, i am working on Consulo.

I am supporting big project (bigger than me). I can't do it inside JetBrains(due limitation their platform, and their policy). And JetBrains not provided all tools & services, which i can "up" it, and forget.

I wrote many services for Consulo. For example - auto-update (and it's not just simple update). 

Nobody paid me (and i got zero dollars every month from Consulo), and Consulo never will commercial product. 

Sorry, but sometimes i can be lazy

Cheers!

PS:
> If you do not see something that does not mean that it does not exist.

**Comment by winalex** [comment]
![clipboard01](https://user-images.githubusercontent.com/689092/34321593-e26d5512-e812-11e7-9288-9512d3658cc6.jpg)
At least I would want to see Filter by extension (why the F* I want .meta)

**Comment by VISTALL** [comment]
Reasonably. You can hide meta files in filter dialog (top right action near pin, and deselect META)

I think i will add it by default.

Thanks
