### ISSUE TITLE
Update fails in case of temporary network instability: need retry before fail

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#318]
- IDE build number: 1937
- Java version: 8
- OS name and version: Win10

In case of temporary network instability (for example, wifi turned off for a couple of seconds and then reconnected) plugin update fails. There should be some reasonable timeout with several retries instead of immediate fail.

**Comment by VISTALL** [comment]
done

**Comment by unv-unv** [comment]
Thanks!

**Comment by VISTALL** [comment]
It's was added with chechsum. It's has few trys, and than fail
