### ISSUE TITLE
Can't change Font settings

### ISSUE THREAD

**Issue by konmal88** [consulo/consulo#331]
- IDE build number: 2061
- Java version: 1.8.0_152
- OS name and version: Ubuntu 18.04

I am trying to change the Font settings in the settings menu.
It says "The ide tries to use the next font from 'Selected fonts' list for displaying a symbol if the current font fails to do that". The fields seem to be **inactive-disabled**.

**Comment by VISTALL** [comment]
Hello. I'm not sure what you mean about. Font reset to default after save ? Yeah presentation of label horrible. 

Thanks

**Comment by konmal88** [comment]
![screenshot](https://user-images.githubusercontent.com/30198524/46494731-40680b00-c81c-11e8-8cbf-3f5ee2685ce0.png)

**Comment by brogan89** [comment]
> The fields seem to be **inactive-disabled**.

This is same thing I didn't notice at first. You need to "Save As..." then you can change font size field.
