### ISSUE TITLE
Cant load vm options

### ISSUE THREAD

**Issue by xahon** [consulo/consulo#334]
- IDE build number: build2090
- Java version: 
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
- OS name and version:  Windows 10

Error when launching consulo.exe or consulo64.exe

**Comment by VISTALL** [comment]
Hello. As fast fix - can you use build with bundled jre?(or with your JRE 8 plus env CONSULO_JRE).

I known about some problems with Java 9+ but always forgot about it(sorry), due small popularity of those jdks (there no problems in runtime, but there some problems with native launchers)


Thanks

**Comment by VISTALL** [comment]
Hello again. I changed launcher for support 9+ jdk(jre). But for now this fix in nightly channel, you can download build via this link https://hub.consulo.io/api/repository/download?channel=nightly&platformVersion=2110&id=consulo-win-no-jre-zip&version=2110&platformBuildSelect=true or select correct artifact here (https://hub.consulo.io/#!repo/nightly/consulo-win-no-jre-zip)


Will be nice if you test it, and give me result :)

Thanks
