### ISSUE TITLE
Main Menu is not working on macOS (10.13 & 10.14)

### ISSUE THREAD

**Issue by TeorikDeli** [consulo/consulo#340]
- IDE build number: 2168 Nightly (but I've this problem since the new main menu)
- Java version: 1.8.0_92
- OS name and version: Both macOS 10.13 & 10.14

It might be related to #335 , but I'm not sure. New Main Menu is not working at all (Already miss the old, classic macOS-type menu 😢 ). For example; I click to File, it's background becomes blue, but nothing happens. I can navigate (with left-right arrows or cursor) between File-Edit-...-Help, but none of them is working. I tried to change my theme from Darcula to Default, but then all the main menu has disappeared. I also tried some keyboard shortcuts while focused on any main menu item, but it doesn't work either.

**Comment by VISTALL** [comment]
Hello. For workaround set to `false` property inside those file (Consulo.app/Contents/consulo.properties)

apple.laf.useScreenMenuBar

it will disable ScreenMenu. I'm not sure way at your Mac menu is not work, but at my - work. I am using 1.8 jdk, and majove. Strange

I will provide fix today(in 24 hours), but i need sleep :) (i came from airport and tired)

**Comment by VISTALL** [comment]
Nope - it's problem of JDK or my implementation. Your jdk is lower than mine - i will test it.  

Anyway it's JDK 8 - and menu must work as expected.

**Comment by VISTALL** [comment]
I pushed fix (return old impl with some proxy). Can you test ? Call Check for update, and enable screenmenu.

**Comment by TeorikDeli** [comment]
Yeah, it's working now. build 2169 and enabled screenmenu.

**Comment by VISTALL** [comment]
thanks
