### ISSUE TITLE
Can't get available plugins list

### ISSUE THREAD

**Issue by cegrosa** [consulo/consulo#344]
- IDE build number: 2179
- Java version: 1.8.0_191-b12
- OS name and version: Windows 10 Home 17134.407

When I access to the list of available plugins I get a certificate error.

I installed java again and tested the versions with/out jre.

![image](https://user-images.githubusercontent.com/27679902/48960550-c62b4b80-ef6d-11e8-9fa9-dc00811a9db7.png)

**Comment by VISTALL** [comment]
Hello. Strange. I returned old certificate (which will end at 4 January) . I will test it before next update.

Thanks

**Comment by VISTALL** [comment]
Fixed. Updated certificate to 2019 year.
