### ISSUE TITLE
Option for changing search engine

### ISSUE THREAD

**Issue by brogan89** [consulo/consulo#353]
- IDE build number: #2199 Nightly
- Java version: 1.8.0_152-release
- OS name and version: Pop!_OS 18.10

As discussed in forum would love ability to change search engine, as Duck Duck Go is becoming more popular now I would like that to be my default search engine. Even if its just a text field where people can write in there own URL.

**Comment by VISTALL** [comment]
Hello i added some popular search engines. Now they can be selected.

![](https://klikr.org/73be0593f1ec7df8cd2773d5e6ed.png)
