### ISSUE TITLE
Pictures in Tip of the Day are corrupted

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#354]
- IDE build number: 2186
- Java version: 1.8
- OS name and version: Win10

Pictures in Tip of the Day are shown as random diagonal lines:
![tip_of_the_day_corrupted_picture](https://user-images.githubusercontent.com/16825982/53170258-c1b81280-35f0-11e9-803f-35df3c7603de.png)

**Comment by VISTALL** [comment]
I think need just disable Tips of Day, due i never update it. It's contains very old images, and need change them. Also most of them contains some IDEA specific implementation.

**Comment by unv-unv** [comment]
Anyway picture display must be fixed :)

**Comment by unv-unv** [comment]
OK, now it seems that this issue is not relevant anymore due to absence of pictures in Tip of the Day dialog.

**Comment by VISTALL** [comment]
Reopened - due I will fix image loading. Outdating image it's another issue
