### ISSUE TITLE
Ctlr+Alt+V performs paste from clipboard instead of Extract Variable refactoring

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#356]
- IDE build number: 2186
- Java version: 1.8
- OS name and version: Win10

Ctlr+Alt+V performs paste from clipboard instead of Extract Variable refactoring.

**Comment by VISTALL** [comment]
Hello. Can you check keymap? (settings -> keymap -> and search Extract Variable?) And also Paste action.

I'm also using nightly build, and there no problem. 

Thanks

**Comment by unv-unv** [comment]
Found source of problem: Punto Switcher. It had Ctrl+Alt+V mapped to "Paste without formatting". Closing this issue.

**Comment by VISTALL** [comment]
👍
