### ISSUE TITLE
Consulo reacts to every second Alt keypress

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#364]
- IDE build number: 2279
- Java version: 1.8
- OS name and version: Win10

On pressing and holding Alt Consulo shows side menus. But somehow it reacts to the first Alt key press, then when I press for the second time it doesn't react and reacts only to the third press.

Video:
[Consulo_reacts_every_second_Alt.zip](https://github.com/consulo/consulo/files/3292710/Consulo_reacts_every_second_Alt.zip)

**Comment by VISTALL** [comment]
Hello. It's works as expected.

You have hidden toolwindow buttons (i forgot its default case or not). And double-alt will show them

Click on button at left-bottom corner - it will show toolwindow buttons, and disable Alt handling

(https://www.jetbrains.com/help/idea/manipulating-the-tool-windows.html#show-all)

**Comment by unv-unv** [comment]
OK, if it's double Alt press+hold, then still it should behave differently. Currently it introduces state switching on each Alt keypress. So if I pressed Alt once in the distant past and doing double Alt press+hold, it won't show toolwindow (because it would show on first Alt press and immediately hide on second Alt press+hold). There should be a timer reset for single Alt press so I would not need to adapt to hidden every-second-Alt state.

**Comment by unv-unv** [comment]
Tested one more time. It seems there is a reset timer, though it is a bit slow for me. Closing.

**Comment by VISTALL** [comment]
😺
