### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by zubovm** [consulo/consulo#377]
- IDE build number: current git master
- Java version: OpenJDK 1.8.0_232
- OS name and version: Linux Manjaro 18.1.5

Accordingly to README.md, typed this at the root of the project
`mvn package 
`
and got this:
[INFO] Scanning for projects...
Downloading from consulo-plugin: https://maven.consulo.io/repository/snapshots/consulo/maven/java9-maven-plugin/1.0-SNAPSHOT/maven-metadata.xml
Downloaded from consulo-plugin: https://maven.consulo.io/repository/snapshots/consulo/maven/java9-maven-plugin/1.0-SNAPSHOT/maven-metadata.xml (778 B at 1.5 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for consulo:consulo-util-rmi:2-SNAPSHOT: Could not find artifact consulo:arch.global:pom:2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for consulo:consulo-util-lang:2-SNAPSHOT: Could not find artifact consulo:arch.global:pom:2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for consulo:consulo-util-collection:2-SNAPSHOT: Could not find artifact consulo:arch.global:pom:2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for consulo:consulo-util-concurrent:2-SNAPSHOT: Could not find artifact consulo:arch.global:pom:2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for consulo:consulo-util-advanced-proxy:2-SNAPSHOT: Could not find artifact consulo:arch.global:pom:2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
[FATAL] Non-resolvable parent POM for consulo:consulo-util-dataholder:2-SNAPSHOT: Could not find artifact consulo:arch.global:pom:2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11

**Comment by VISTALL** [comment]
Hello. Looks like i have wrong path in poms. I will fix it now

**Comment by VISTALL** [comment]
Pull last version. Must be ok
