### ISSUE TITLE
Does not run as a desktop application

### ISSUE THREAD

**Issue by zubovm** [consulo/consulo#378]
- IDE build number: current git master
- Java version: 1.8.0_232
- OS name and version: Linux Manjaro 18.1.5

After 
`mvn install
mvn consulo:run -pl:consulo-sandbox-desktop`
it prints:
Unable to parse command line options: Unrecognized option: -pl:consulo-sandbox-desktop

**Comment by VISTALL** [comment]
Hi. Try. I forgot update it after plugin change (and also update to last mvn spec) 

`mvn consulo:run-desktop -pl consulo:consulo-sandbox-desktop`
