### ISSUE TITLE
New UI Overflow texts.

### ISSUE THREAD

**Issue by parmaia** [consulo/consulo#383]
After the UI update, some texts are overflowing their container and are no longer visible:

![image](https://user-images.githubusercontent.com/2512986/81553454-61dc9180-9385-11ea-97de-bca540f9edbc.png)
_Commit Dialog_

![image](https://user-images.githubusercontent.com/2512986/81553614-b41db280-9385-11ea-9dd1-0154e0f0d5f0.png)
_Fast search (triple-shift-press)_

![image](https://user-images.githubusercontent.com/2512986/81555562-15935080-9389-11ea-9299-27ff8fe790fa.png)
_Push Dialog_

I can't remember if there are other places (I think I saw this in other places, but can't find them).

 **Consulo**:
  version = 2020.2
  build number = 2483
  build date = February 16, 2020

 **JVM**:
  vendor = Oracle Corporation
  version = 1.8.0_131
  runtimeVersion = 1.8.0_131-b11

**Windows** 10.0.18362 compilación 18362

**Comment by VISTALL** [comment]
Hello. Can you update jdk? it's too old. Also - i'm in deprecation JRE 8 runtime, i think no sense fixing this issue, if it reproduced only at with build..

Thanks

**Comment by parmaia** [comment]
Hi,

I downloaded the Consulo version shipped with jdk, just to test, and the result is the same.

Tomorrow I'll update my jdk and let you know.

**Comment by parmaia** [comment]
Well, I updated the jdk version:

 JVM:
  vendor = Oracle Corporation
  version = 14.0.1
  runtimeVersion = 14.0.1+7
  locale = es_ES

But still having the issue with the UI.

**Comment by VISTALL** [comment]
Thanks, I will test it, in near future. Strange anyway

**Comment by VISTALL** [comment]
I checked. There a problem with button implementation and new ui impl. Reproduced. 

About Fast-Search, it's another issue, for now i can't reproduce that.

**Comment by VISTALL** [comment]
I pushed some test fix. It's compromise between my UI and IDEA UI.

**Comment by VISTALL** [comment]
closed - if found new issue, report it
