### ISSUE TITLE
Add Ctrl+Shift+T hotkey for reopening just closed tab

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#395]
All browsers now support standard hotkey for reopening just closed tab: Ctrl+Shift+T.

Would be nice if Consulo also had such a hotkey.

**Comment by YT-GameWorks** [comment]
I don't really use hotkeys that much, but are you sure there already isn't? if not, then you can change it, in `Settings->keymaps`

**Comment by YT-GameWorks** [comment]
correcting: `Settings->General->Keymaps`

**Comment by unv-unv** [comment]
Thanks, it works.

**Comment by unv-unv** [comment]
Keymap action location:
Main menu / Window / Editor Tabs / Reopen Closed Tab
