### ISSUE TITLE
After update checker restarts Consulo, reopen all windows for multiple projects

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#396]
If I have several windows with different projects open and I run Update Checker and run update, then after Consulo restart only one of the windows is reopened. Could you reopen all the windows which were open when update was run?

**Comment by VISTALL** [comment]
I think you are right.

**Comment by VISTALL** [comment]
Pushed test change - i will control it, and close this issue if satisfy me

**Comment by unv-unv** [comment]
Windows are reopened OK, but Tip of the Day is triggered for each window.

**Comment by VISTALL** [comment]
Yeah, it's correct logic due tips dialog showed for each project

**Comment by unv-unv** [comment]
I click File > Open Recent, select some project. It opens and Tips of the Day dialog is not shown.

**Comment by unv-unv** [comment]
Moreover, I think, Consulo restart after plugin update should not trigger Tip of the Day at all. This is a technical restart after all. As user, I expect the program to continue work after plugin update as seamlessly as it can.

**Comment by VISTALL** [comment]
I saw - Tips of day, not work correct with multiple project opening (i fixed another issue with same problem)

Fill fix it

**Comment by VISTALL** [comment]
Reworked showing tip of day, also fix old hack
