### ISSUE TITLE
Extract Method shows zero-height Name input

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#397]
```
    public static Object requestGridControl(Element args) throws Exception
    {
        List<String> multipleValues = new ArrayList<String>();
        for (Object multipleValue : args.getChildren("MultipleValue"))
        {
            multipleValues.add(((Element) multipleValue).getText());
        }
    }
```

Selecting "for" cycle and pressing Ctrl+Alt+M. Invalid method creation dialog is shown: no ability to specify method name.

![изображение](https://user-images.githubusercontent.com/16825982/85833443-6543a500-b79a-11ea-9829-f4c2d1c18f7c.png)

**Comment by VISTALL** [comment]
Hello. Thanks for error, i saw this problem (it's related to last editor changes) and bug can saw in rename dialog, etc
