### ISSUE TITLE
SDK libraries not loaded after restart

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#402]
After last nightly update all basic java classes (like String, Exception, etc.) are highlighted as errors.

One more time I ask you to have a simple rollback mechanism for switching from latest nightly builds to release build in case of critical errors introduced by development. It's the second big usability issue in a week, together with breaking opening of JSP files.

**Comment by VISTALL** [comment]
I move this issue to platform - maybe after some time, i catch and fix it

**Comment by VISTALL** [comment]
One question - selected SDK was predefined? (auto-created)

**Comment by unv-unv** [comment]
Hard to say, it was a while ago.

**Comment by unv-unv** [comment]
Let's close this one. I'll reopen it if it repeats.
