### ISSUE TITLE
In Darcula theme selected tab is almost indistinguishable from others

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#404]
- IDE build number: 2599
- Java version: Java8
- OS name and version: Win10

![изображение](https://user-images.githubusercontent.com/16825982/91259172-a47c7b00-e776-11ea-8e33-77e12d20c508.png)

**Comment by VISTALL** [comment]
Hello. Sure. I had updated style, due it's had many paint bugs. Looks like need make it more darker or lighter, not sure 

Thanks for notify
