### ISSUE TITLE
Can't apply font settings?

### ISSUE THREAD

**Issue by ElnuDev** [consulo/consulo#412]
After duplicating a theme in the settings, one can go to Settings > Colors & Fonts > Console Font and change the size/font. However, after hitting apply, they only are used in the preview. Any clue what's going on? Is this a bug?

**Comment by VISTALL** [comment]
Hello. It works as expected. Here i downloaded Consulo from scratch and all works as expected 

https://www.youtube.com/watch?v=O3ST-HvUnCs

**Comment by ElnuDev** [comment]
I was looking in the wrong place yesterday! I was looking in Console Font instead of Font. I wanted to change the code font size, not the console font size. Sorry about that!

Also, thank you so much for making Consulo. It's the only code editor I can get working with Unity on Linux. I really appreciate it!
