### ISSUE TITLE
Update broke Consulo

### ISSUE THREAD

**Issue by Balroth** [consulo/consulo#418]
I got an IDE error with Consulo
Then it said something about plugins, to update them or something (4 days old update)
I update them, it asks for restart now or postpone
I restart now.

I got pic-related
Also happens whenever I open Consulo, can't even open it by itself :(
![15](https://user-images.githubusercontent.com/25630803/95631370-425ca880-0a8c-11eb-880f-8c3fbd406576.PNG)

I am on Windows 7
Unity 2018.1.1f1

Aside of fixing it permanently whenever you have time, do you have a quick suggestion to open Consulo with Unity as normally it was before? Something to "reset" it before the updates, until this is fixed?

Also side-question, does Consulo synchronize constantly with Unity? Because it doesn't make much sense for Consulo to get IDE Errors when I just type something :(
If it does synchronize automatically, can I make the synchronization manual every time I save?

**Comment by Balroth** [comment]
No rush :)

**Comment by VISTALL** [comment]
Good morning. I fixed downloading Consulo. You can download(or update)

**Comment by Balroth** [comment]
Thanks, on my way! <3

**Comment by VISTALL** [comment]
Problem fixed? If yes sorry for this problem, sometimes i catch unexpected problems with server. Anyway thanks for notify, i handle all :)

**Comment by Balroth** [comment]
Yes, it is fixed, also do not apologize, especially since you were the one who fixed it, and so fast! :tada:
