### ISSUE TITLE
new C# file icons

### ISSUE THREAD

**Issue by YT-GameWorks** [consulo/consulo#426]
I made (ripped off rider) 2 new icons for C# and unity MonoBehaviour. since the current one is just from IntelliJ idea and looks kinda out of date.
Here they are: 
![Consulo_new_C#_logo_bg](https://user-images.githubusercontent.com/39207327/97283326-b5746600-1865-11eb-960e-07738fbb75ce.png)
This is the base, normal C# file. Here is one for unity Monobehaviour:
![Consulo_new_C#_logo_with_unity_bg](https://user-images.githubusercontent.com/39207327/97283435-db016f80-1865-11eb-9c41-079a4ed131a9.png)
You can use these exact one if you want! but here are the photoshop files in case you wanna modify it your self. I think I don't know enough about java or software to commit to this repo... Maybe one day!

Here are the [photoshop files](https://uploadhub.co/66cf8da81fc274bcb13566614fdc0a6a/Consulo_new_icons.zip).

**Comment by VISTALL** [comment]
Hello. Thanks for you suggestion, but i will refuse current suggestion. Why.

First of all i wanna update all icons from IDEA but with my fixes. File icons not updated for now, due i have ,any icons which is need make by self.

But - there one thing. I have new functional named "Icon Theme", plugins can provide own icons.

Later i want add Visual Studio icon theme from public Visual Studio Image Library (https://www.microsoft.com/en-us/download/details.aspx?id=35825).  But there one thing. Each icon need repack to inline svg attributes (svg is prefer over png, due it have better scaler options).

If you want - i can create plugin, with VS icons (only few, due i don't want lose time for it) and you can update it, and then use plugin.

**Comment by YT-GameWorks** [comment]
> If you want - i can create plugin, with VS icons (only few, due i don't want lose time for it) and you can update it, and then use plugin.

That would be awesome! btw have you considered making a public [trello
](https://trello.com) ? It is a site where you can organise tasks and lots of cool stuff! If you already have one, can I get the link 😄 ? If you do make the plugin, I'll be happy to update it with many of my vs code favourites and others! although ill have to relearn java cuz it's been 2 years since I've written java (assuming that the majority of that plugin might be written in java). Thanks!

**Comment by VISTALL** [comment]
Github have own small trello implementation. 

https://github.com/orgs/consulo/projects

But it's hard for me control this list, due when i don't have ideas for some issues - i'm moved to another plugin.

Too many plugins, which i want. Too many issues for one person :D 

Thanks, i will create new icon plugin now.

**Comment by VISTALL** [comment]
Also i have project like this https://github.com/consulo/long-term-todo/issues

**Comment by YT-GameWorks** [comment]
Yea, I feel you! This is such a big project for 1 person, I am trying to help by implementing few features ( or trying to ) like this one :D also I know that GitHub has its own implementation but it is quite limited.... I recommend trello more as you can organise stuff way faster and divide them up, making it very organised and easier to keep track of ! You can make lists for all the repos in one place instead of GitHub projects in every repo, ( I don't know if you actually do make projects in all repos ) so just a friendly suggestion, give trello a shot ( it has plugins too ! I use custom fields plugin the most ) it will make the development faster, I think!

Anyway, you do you ! 
Thanks.

**Comment by VISTALL** [comment]
Short list

https://github.com/consulo/EntryPoint/tree/master/repositories

**Comment by VISTALL** [comment]
Initial version.

https://github.com/consulo/incubating-consulo-visual-studio-theme

I am writing readme for it

**Comment by YT-GameWorks** [comment]
> Initial version.
> 
> https://github.com/consulo/incubating-consulo-visual-studio-theme
> 
> I am writing readme for it

thanks a lot! But currently, consulo is just crashing, #427 issue
