### ISSUE TITLE
VS Code Keymap

### ISSUE THREAD

**Issue by TCROC** [consulo/consulo#461]
VS Code keymap per our Discord conversation: https://discord.com/channels/769309696351666187/813080914761351209/828266673454186556.  

Opening an issue on GitHub for tracking purposes:

These are the 2 links I sent you.  They seem old and out of date:

https://plugins.jetbrains.com/plugin/12062-vscode-keymap

https://github.com/bulenkov/VSCodeKeymap4IntelliJ

This is the one you (@VISTALL) found that seems more recent and up to date:

https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/keymaps/VSCode.xml

Figured I would just include all the links in case they proved useful.  I think that 3rd one is probably the one to use though.

**Comment by VISTALL** [comment]
Added keymaps
