### ISSUE TITLE
In «Rename Constructor Parameters» dialog hovering mouse over checkbox leads to checkbox displacement

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#473]
- IDE build number: 2974
- Java version: 1.8
- OS name and version: Win10

Rename field name which has same-named parameter in the constructor of this class. Then «Rename Constructor Parameters» dialog appears which suggests renaming constructor parameter. Hover mouse over checkbox. Checkbox moves.

![изображение](https://user-images.githubusercontent.com/16825982/135635660-26fce30c-9d54-4ffa-b09a-b4af0c016aad.png)

**Comment by VISTALL** [comment]
Hello. I will check it after my vacation (around 4 days left).
Thanks

**Comment by VISTALL** [comment]
Hello. Tested. Reproduced. Funny :)

**Comment by VISTALL** [comment]
This bug exists in all UI with Dark theme, and checkbox in table
