### ISSUE TITLE
Error highlighting pane next to scroll bar is not synced with scroll bar

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#497]
![изображение](https://user-images.githubusercontent.com/16825982/144193189-89370818-a92b-497b-9c63-77e66033a9a7.png)

When I click on something on this pane this leads to scrolling to this location but scroll bar is way out of Y coordinate of mouse.

**Comment by VISTALL** [comment]
Hello. At least need count lines inside file, and position of todo for reproduce

**Comment by unv-unv** [comment]
Total lines: 2495
TODO position: 1497

**Comment by VISTALL** [comment]
![fd000a5f6a6f96cd4c9f7c1f96c3](https://user-images.githubusercontent.com/542934/144688618-90df0346-95b2-4d63-bd44-b171e0e40030.png)

![cc7c3d1ebde18a3393d46214c0d5](https://user-images.githubusercontent.com/542934/144688594-826b26eb-72f3-44d2-af40-6ecc2a5a49bc.png)

**Comment by VISTALL** [comment]
And same for Dark theme. What font you use?
