### ISSUE TITLE
Auto-unsplit if one of split halves has no tabs

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo#499]
1. Right-click on current editor tab and select "Split Vertically".
2. In the right editor pane right-click on current tab and select "Close".

**Expected Result**: automatic unsplit since no tabs are left on the right side.

**Actual Result**: empty right pane is shown.

![image](https://user-images.githubusercontent.com/16825982/144564858-081fa4e3-b064-4fd4-878e-09d37f386297.png)

**Comment by VISTALL** [comment]
Looks like bug with closing editor in split mode
