### ISSUE TITLE
Cannot Import Project, SDK/Bundles/Tools empty, Cannot Import SDK

### ISSUE THREAD

**Issue by minionprocyk** [consulo/consulo#546]
- IDE build number: 3412
- Java version: 17, 21, 22
- OS name and version: Fedora 40 x86_64

I have tried pretty exhaustively to get this IDE to load a UnityProject, but in fact I can't get the IDE to work even with a fresh project. After loading consulo and installing the Unity plugin all I get are these errors:

[10:50:44.142] ERROR - .internal.plugin.PluginsLoader - Consulo 2023.12  Build #3412 
[10:50:44.142] ERROR - .internal.plugin.PluginsLoader - JDK: 21.0.3 
[10:50:44.142] ERROR - .internal.plugin.PluginsLoader - VM: OpenJDK 64-Bit Server VM 
[10:50:44.142] ERROR - .internal.plugin.PluginsLoader - Vendor: Red Hat, Inc. 
[10:50:44.142] ERROR - .internal.plugin.PluginsLoader - OS: Linux 
[10:50:44.142] ERROR - .internal.plugin.PluginsLoader - Original exception:  
java.lang.IllegalArgumentException: consulo.unity3d.cg.shader.2.SNAPSHOT: Invalid module name: '2' is not a Java identifier

Note that these errors occur with the embedded jdk (17), and my home jdk of 17, 21, and 22. I tried following the documentation for steps to import a unity project and not only does the IDE not allow me to import the project due to the confirm button being greyed out, but the sdk/bundles/tools option is always empty and I cannot click add/new because  the button menu does not work either. When I click the button nothing happens, if I activate the keyboard shortcut hotkey nothing happens. 

I was also trying to find a stable build i could try? Everything seems to be tagged with build numbers I'd be happy to try an older version if there's a confirmed stable build.

**Comment by VISTALL** [comment]
Hello. Yeah looks like plugins from old version. Can you call Help -> Check For updates? It will update plugins

**Comment by minionprocyk** [comment]
The plugins were just installed today. I just tried clicking Help -> Check For updates and it reports no updates

**Comment by VISTALL** [comment]
Can you attach info from About? There will be list of plugins

**Comment by minionprocyk** [comment]
Consulo:
  version = 2023.12
  build number = 3412
  build date = December 18, 2023
 Plugins:
  com.intellij.xml = 3246
  consulo = 3412
  consulo.csharp = 6155
  consulo.desktop.awt = 3412
  consulo.dotnet = 3986
  consulo.dotnet.core = 9324
  consulo.dotnet.mono = 4996
  consulo.javascript = 3906
  consulo.msbuild = 7360
  consulo.nunit = 5790
  consulo.unity3d = 10126
  org.jetbrains.plugins.yaml = 2645
 JVM:
  vendor = Red Hat, Inc.
  version = 17.0.11
  runtimeVersion = 17.0.11+9
  locale = en_US
 JVM Env:
  awt.useSystemAAFontSettings = lcd
  consulo.home.path = ./platform/build3412
  consulo.module.path.boot = true
  consulo.properties.file = ./consulo.properties
  consulo.restart.code = 88
  consulo.vm.options.file = ./consulo64.vmoptions
  file.encoding = UTF-8
  file.separator = /
  idea.cycle.buffer.size = 1024
  idea.dynamic.classpath = false
  idea.home.path = ./platform/build3412
  idea.max.intellisense.filesize = 2500
  idea.no.launcher = false
  idea.popup.weight = heavy
  idea.properties.file = ./consulo.properties
  idea.use.default.antialiasing.in.editor = false
  io.netty.machineId = 28:f0:76:ff:fe:16:65:0e
  io.netty.processId = 15771
  io.netty.serviceThreadPrefix = Netty 
  java.class.path = 
  java.class.version = 61.0
  java.home = /usr/lib/jvm/java-17-openjdk-17.0.11.0.9-1.fc40.x86_64
  java.io.tmpdir = /tmp
  java.library.path = ./platform/build3412/bin:./platform/build3412/bin::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
  java.net.preferIPv4Stack = true
  java.rmi.server.disableHttp = true
  java.rmi.server.hostname = localhost
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.11+9
  java.security.manager = consulo.container.impl.securityManager.impl.ConsuloSecurityManager
  java.specification.name = Java Platform API Specification
  java.specification.vendor = Oracle Corporation
  java.specification.version = 17
  java.util.concurrent.ForkJoinPool.common.parallelism = 32
  java.util.concurrent.ForkJoinPool.common.threadFactory = consulo.bootstrap.concurrent.IdeaForkJoinWorkerThreadFactory
  java.vendor = Red Hat, Inc.
  java.vendor.url = https://www.redhat.com/
  java.vendor.url.bug = https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk&version=38
  java.vendor.version = (Red_Hat-17.0.11.0.9-1)
  java.version = 17.0.11
  java.version.date = 2024-04-16
  java.vm.compressedOopsMode = 32-bit
  java.vm.info = mixed mode, sharing
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.name = Java Virtual Machine Specification
  java.vm.specification.vendor = Oracle Corporation
  java.vm.specification.version = 17
  java.vm.vendor = Red Hat, Inc.
  java.vm.version = 17.0.11+9
  javax.swing.rebaseCssSizeMap = true
  jb.vmOptionsFile = ./consulo64.vmoptions
  jdk.debug = release
  jdk.module.main = consulo.desktop.awt.bootstrap
  jdk.module.main.class = consulo.desktop.awt.boot.main.Main
  jdk.module.path = ./platform/build3412/boot
  jna.loaded = true
  jna.nosys = true
  jna.platform.library.path = /usr/lib64:/lib64:/usr/lib:/lib:/usr/lib64/dyninst:/usr/lib64/mysql:/usr/lib64/iscsi:/usr/lib64/llvm17/lib:/usr/lib64/llvm16/lib:/usr/lib/llvm16/lib:/usr/lib64/llvm15/lib:/usr/lib64/llvm13/lib:/opt/amdgpu-pro/amf/lib64:/usr/lib64/tcl8.6:/usr/lib64/qt5-qtwebengine-freeworld:/usr/i686-w64-mingw32/lib:/usr/x86_64-w64-mingw32/lib
  jna.tmpdir = /home/poweruser/.consulo_settings/system/tmp
  jnidispatch.path = /home/poweruser/.consulo_settings/system/tmp/jna2638142375928022542.tmp
  line.separator = \n
  log4j.shutdownHookEnabled = false
  log4j2.messageFactory = org.apache.logging.log4j.message.SimpleMessageFactory
  native.encoding = UTF-8
  os.arch = amd64
  os.name = Linux
  os.version = 6.8.7-300.fc40.x86_64
  path.separator = :
  sun.arch.data.model = 64
  sun.awt.datatransfer.timeout = 2000
  sun.awt.enableExtraMouseButtons = true
  sun.awt.exception.handler = consulo.desktop.awt.application.impl.AWTExceptionHandler
  sun.awt.noerasebackground = true
  sun.boot.library.path = /usr/lib/jvm/java-17-openjdk-17.0.11.0.9-1.fc40.x86_64/lib
  sun.cpu.endian = little
  sun.font.fontmanager = sun.awt.X11FontManager
  sun.io.unicode.encoding = UnicodeLittle
  sun.io.useCanonCaches = false
  sun.java.command = consulo.desktop.awt.bootstrap/consulo.desktop.awt.boot.main.Main
  sun.java.launcher = SUN_STANDARD
  sun.java2d.d3d = false
  sun.java2d.noddraw = true
  sun.java2d.pmoffscreen = false
  sun.java2d.uiScale.enabled = true
  sun.jnu.encoding = UTF-8
  sun.management.compiler = HotSpot 64-Bit Tiered Compilers
  sun.nio.ch.bugLevel = 
  sun.stderr.encoding = UTF-8
  sun.stdout.encoding = UTF-8
  swing.bufferPerWindow = false
  user.country = US
  user.dir = /media/big_drive/media/Downloads/consulo.dist.linux.no.jre_3412/Consulo
  user.home = /home/poweruser
  user.language = en
  user.name = poweruser
  user.timezone = America/New_York
 OS:
  name = Linux
  version = 6.8.7-300.fc40.x86_64
  arch = amd64
 Env:
  ALL_JVM_ARGS = -Djava.security.manager=consulo.container.impl.securityManager.impl.ConsuloSecurityManager --add-opens=java.desktop/sun.awt=consulo.container.impl --add-opens=java.desktop/sun.swing=consulo.container.impl --add-opens=java.desktop/sun.awt.image=consulo.container.impl --add-opens=java.desktop/sun.java2d=consulo.container.impl --add-opens=java.desktop/sun.font=consulo.container.impl --add-opens=java.desktop/sun.awt.datatransfer=consulo.container.impl --add-opens=java.desktop/sun.awt.X11=consulo.container.impl --add-opens=java.desktop/java.awt=consulo.container.impl --add-opens=java.desktop/javax.swing=consulo.container.impl --add-opens=java.desktop/javax.swing.plaf.basic=consulo.container.impl --add-opens=java.base/java.lang=consulo.container.impl --add-opens=java.desktop/javax.swing.text.html=consulo.container.impl --add-opens=java.desktop/java.awt.peer=consulo.container.impl --add-opens=java.desktop/java.awt.event=consulo.container.impl --add-opens=java.desktop/com.apple.laf=consulo.container.impl --add-opens=java.desktop/com.apple.eawt=consulo.container.impl --add-opens=java.desktop/com.apple.eawt.event=consulo.container.impl  -Xms512m -Xmx1500m -XX:ReservedCodeCacheSize=240m -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=50 -XX:+HeapDumpOnOutOfMemoryError -Dawt.useSystemAAFontSettings=lcd  -Djb.vmOptionsFile="./consulo64.vmoptions" -Dconsulo.vm.options.file="./consulo64.vmoptions" -p "./platform/build3412/boot" -Dconsulo.module.path.boot=true -Dconsulo.home.path="./platform/build3412" -Didea.home.path="./platform/build3412" -Didea.properties.file="./consulo.properties" -Dconsulo.properties.file="./consulo.properties"   
  AMD_VULKAN_ICD = amdvlk-pro
  ANDROID_HOME = /home/poweruser/dev/Android/SDK
  ANDROID_SDK_ROOT = /home/poweruser/dev/Android/SDK
  COLORTERM = truecolor
  CONDA_SHLVL = 0
  CONSULO_HOME = ./platform/build3412
  DBUS_SESSION_BUS_ADDRESS = unix:path=/run/user/1000/bus
  DEBUGINFOD_URLS = https://debuginfod.fedoraproject.org/ 
  DESKTOP_SESSION = gnome
  DEVWINE = /home/poweruser/dev/C++/git/wine
  DISPLAY = :0
  DOTNET_BUNDLE_EXTRACT_BASE_DIR = /home/poweruser/.cache/dotnet_bundle_extract
  DOTNET_ROOT = /usr/lib64/dotnet
  EDITOR = /usr/bin/nano
  GDMSESSION = gnome
  GDM_LANG = en_US.UTF-8
  GEM_HOME = /home/poweruser/.rvm/gems/ruby-2.7.0
  GEM_PATH = /home/poweruser/.rvm/gems/ruby-2.7.0:/home/poweruser/.rvm/gems/ruby-2.7.0@global
  GNOME_TERMINAL_SCREEN = /org/gnome/Terminal/screen/f336a317_da9c_4c69_82de_4a79df4af401
  GNOME_TERMINAL_SERVICE = :1.220
  GUESTFISH_INIT = \\e[1;34m
  GUESTFISH_OUTPUT = \\e[0m
  GUESTFISH_PS1 = \\[\\e[1;32m\\]><fs>\\[\\e[0;31m\\] 
  GUESTFISH_RESTORE = \\e[0m
  HISTCONTROL = ignoreboth
  HISTSIZE = 1000
  HOME = /home/poweruser
  HOSTNAME = power
  IMSETTINGS_INTEGRATE_DESKTOP = yes
  IMSETTINGS_MODULE = User Specific
  INSIDE_NAUTILUS_PYTHON = 
  IRBRC = /home/poweruser/.rvm/rubies/ruby-2.7.0/.irbrc
  JAVA_HOME = /usr/lib/jvm/java-17-openjdk
  JDK = /usr/lib/jvm/java-17-openjdk
  KDEDIRS = /usr
  LANG = en_US.UTF-8
  LD_LIBRARY_PATH = ./platform/build3412/bin:./platform/build3412/bin:
  LESSOPEN = ||/usr/bin/lesspipe.sh %s
  LOADEDMODULES = 
  LOGNAME = poweruser
  LS_COLORS = rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:
  MAIL = /var/spool/mail/poweruser
  MAIN_CLASS_NAME = -m consulo.desktop.awt.bootstrap/consulo.desktop.awt.boot.main.Main
  MANPATH = /usr/share/man:
  MEMORY_PRESSURE_WATCH = /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/dbus-:1.2-org.gnome.Nautilus@2.service/memory.pressure
  MEMORY_PRESSURE_WRITE = c29tZSAyMDAwMDAgMjAwMDAwMAA=
  MODULEPATH = /etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
  MODULESHOME = /usr/share/Modules
  MODULES_CMD = /usr/share/Modules/libexec/modulecmd.tcl
  MODULES_RUN_QUARANTINE = LD_LIBRARY_PATH LD_PRELOAD
  MOZ_GMP_PATH = /usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed
  MY_RUBY_HOME = /home/poweruser/.rvm/rubies/ruby-2.7.0
  PATH = /home/poweruser/Downloads/platform-tools_r34.0.5-linux/platform-tools:/home/poweruser/.cargo/bin:/home/poweruser/.local/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/home/poweruser/Downloads/platform-tools_r34.0.5-linux/platform-tools:/home/poweruser/.rvm/gems/ruby-2.7.0/bin:/home/poweruser/.rvm/gems/ruby-2.7.0@global/bin:/home/poweruser/.rvm/rubies/ruby-2.7.0/bin:/home/poweruser/.cargo/bin:/home/poweruser/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/lib/dart/bin:/usr/local/bin/flutter/bin:/home/poweruser/.rvm/bin:/home/poweruser/.rvm/bin:/home/poweruser/.rvm/bin:/home/poweruser/.local/share/JetBrains/Toolbox/scripts:/home/poweruser/.dotnet/tools:/usr/lib/dart/bin:/usr/local/bin/flutter/bin:/home/poweruser/.rvm/bin:/home/poweruser/.rvm/bin:/home/poweruser/.rvm/bin:/home/poweruser/.local/share/JetBrains/Toolbox/scripts:/home/poweruser/.local/share/JetBrains/Toolbox/scripts:/home/poweruser/.rvm/bin:/home/poweruser/.rvm/bin:/home/poweruser/.rvm/bin
  PWD = /home/poweruser/Downloads/consulo.dist.linux.no.jre_3412/Consulo
  QT_IM_MODULE = ibus
  ROOT_DIR = .
  RUBY_VERSION = ruby-2.7.0
  SDKMAN_DIR = /home/poweruser/.sdkman
  SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS = 0
  SESSION_MANAGER = local/unix:@/tmp/.ICE-unix/2531,unix/unix:/tmp/.ICE-unix/2531
  SHELL = /bin/bash
  SHLVL = 2
  SSH_AGENT_PID = 2424
  SSH_ASKPASS = /usr/libexec/openssh/gnome-ssh-askpass
  SSH_AUTH_SOCK = /tmp/ssh-XXXXXXShRLZv/agent.2230
  STEAM_FRAME_FORCE_CLOSE = 1
  SYSTEMD_EXEC_PID = 10532
  TERM = xterm-256color
  USER = poweruser
  USERNAME = poweruser
  VTE_VERSION = 7601
  WINDOWPATH = 2
  XAUTHORITY = /run/user/1000/gdm/Xauthority
  XDG_CURRENT_DESKTOP = GNOME
  XDG_DATA_DIRS = /home/poweruser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
  XDG_MENU_PREFIX = gnome-
  XDG_RUNTIME_DIR = /run/user/1000
  XDG_SESSION_CLASS = user
  XDG_SESSION_DESKTOP = gnome
  XDG_SESSION_TYPE = x11
  XMODIFIERS = @im=none
  _ = /usr/lib/jvm/java-17-openjdk/bin/java
  __MODULES_LMINIT = module use --append /usr/share/Modules/modulefiles:module use --append /etc/modulefiles:module use --append /usr/share/modulefiles
  __MODULES_SHARE_MANPATH = :1
  rvm_bin_path = /home/poweruser/.rvm/bin
  rvm_loaded_flag = 1
  rvm_path = /home/poweruser/.rvm
  rvm_prefix = /home/poweruser
  rvm_stored_umask = 0022
  rvm_user_install_flag = 1
  rvm_version = 1.29.10 (latest)

**Comment by VISTALL** [comment]
Checked binary for this plugin 
![image](https://github.com/consulo/consulo/assets/542934/a406b8a0-2518-4e92-bcfe-efebc13180c7)
there no old 2.0 versions (which is in log)

Can you show me screenshot of this page? 
![image](https://github.com/consulo/consulo/assets/542934/d9e94a35-f87a-4f5a-abba-c3ebe5db7e93)

Also show me content of directory  `/home/poweruser/.consulo_settings/config/plugins/consulo.unity3d`

**Comment by minionprocyk** [comment]
![image](https://github.com/consulo/consulo/assets/8663534/83c4e1f1-0ee5-4e63-8feb-00e68c86cceb)

**Comment by minionprocyk** [comment]
ll /home/poweruser/.consulo_settings/config/plugins/consulo.unity3d
total 24
drwxr-xr-x.  6 poweruser libvirt 4096 Jun  8 10:06 ./
drwxr-xr-x. 32 poweruser libvirt 4096 Jun  8 11:06 ../
drwxr-xr-x.  3 poweruser libvirt 4096 Jul 28  2019 externalAttributes/
drwxr-xr-x.  2 poweruser libvirt 4096 Jun  8 10:06 lib/
drwxr-xr-x.  2 poweruser libvirt 4096 Jun  8 10:06 META-INF/
drwxr-xr-x.  2 poweruser libvirt 4096 Jul 28  2019 UnityEditorConsuloPlugin/

**Comment by VISTALL** [comment]
List `lib` files please

**Comment by minionprocyk** [comment]
consulo.unity3d-2-SNAPSHOT.jar            consulo.unity3d-uss.impl-3-SNAPSHOT.jar
consulo.unity3d-3-SNAPSHOT.jar            consulo.unity3d-uss.impl-3-SNAPSHOT.jar.requires
consulo.unity3d-cg.shader-2-SNAPSHOT.jar  consulo.unity3d-uxml.impl-3-SNAPSHOT.jar
consulo.unity3d-cg.shader-3-SNAPSHOT.jar  consulo.unity3d-uxml.impl-3-SNAPSHOT.jar.requires
consulo.unity3d-shaderlab-2-SNAPSHOT.jar  dd-plist-1.20.jar
consulo.unity3d-shaderlab-3-SNAPSHOT.jar

**Comment by VISTALL** [comment]
Looks like this is new plugin. Can you delete`.consulo_settings`, and `Consulo`, and redownload it from scratch ?

**Comment by minionprocyk** [comment]
Thanks, upon scrubbing and re-doing. I was met with an initial import prompt which guided me through downloaded the plugins which was new, importing seemed to work and generally the ide seemed like it started working! 

thanks for your help!

**Comment by minionprocyk** [comment]
For completeness, and hopefully this didn't change anything. I conveniently also finished cloning the project and running mvn package. I'm not sure if that may have installed some artifacts required for the change in experience, but I can finally try to do some work now. So i'm going to leave it as is

**Comment by VISTALL** [comment]
Good. You can ask me anything if found errors. Good day for you
