### ISSUE TITLE
Need fix

### ISSUE THREAD

**Issue by coderhasib2021** [consulo/consulo#603]
- IDE build number: consulo.dist.linux64_3570.tar.gz
- Java version: 17
- OS name and version: Operating System: Parrot Security 6.2 (lorikeet)  
                                       Kernel: Linux 6.9.7-amd64
                                       Architecture: x86-64
 Consulo:
  version = 2024.8
  build number = 3570
  build date = August 19, 2024
 Plugins:
  consulo = 3570
  consulo.desktop.awt = 3570
 JVM:
  vendor = JetBrains s.r.o.
  version = 21.0.2
  runtimeVersion = 21.0.2+13-b375.1
  locale = en_US
 JVM Env:
  awt.toolkit.name = XToolkit
  awt.useSystemAAFontSettings = lcd
  consulo.home.path = ./platform/build3570
  consulo.module.path.boot = true
  consulo.properties.file = ./consulo.properties
  consulo.restart.code = 88
  consulo.vm.options.file = ./consulo64.vmoptions
  file.encoding = UTF-8
  file.separator = /
  idea.cycle.buffer.size = 1024
  idea.dynamic.classpath = false
  idea.home.path = ./platform/build3570
  idea.max.intellisense.filesize = 2500
  idea.no.launcher = false
  idea.popup.weight = heavy
  idea.properties.file = ./consulo.properties
  idea.use.default.antialiasing.in.editor = false
  io.netty.machineId = 28:f0:76:ff:fe:16:65:0e
  io.netty.processId = 39873
  io.netty.serviceThreadPrefix = Netty 
  java.class.path = 
  java.class.version = 65.0
  java.home = /media/system76/WD-BACKUP/Hasibul\'s-World/IDE/Consulo/platform/build3570/jre
  java.io.tmpdir = /tmp
  java.library.path = ./platform/build3570/bin::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
  java.net.preferIPv4Stack = true
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 21.0.2+13-b375.1
  java.security.manager = consulo.container.impl.securityManager.impl.ConsuloSecurityManager
  java.specification.name = Java Platform API Specification
  java.specification.vendor = Oracle Corporation
  java.specification.version = 21
  java.util.concurrent.ForkJoinPool.common.parallelism = 4
  java.util.concurrent.ForkJoinPool.common.threadFactory = consulo.bootstrap.concurrent.IdeaForkJoinWorkerThreadFactory
  java.vendor = JetBrains s.r.o.
  java.vendor.url = https://openjdk.org/
  java.vendor.url.bug = https://bugreport.java.com/bugreport/
  java.vendor.version = JBR-21.0.2+13-375.1-nomod
  java.version = 21.0.2
  java.version.date = 2024-01-16
  java.vm.compressedOopsMode = 32-bit
  java.vm.info = mixed mode
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.name = Java Virtual Machine Specification
  java.vm.specification.vendor = Oracle Corporation
  java.vm.specification.version = 21
  java.vm.vendor = JetBrains s.r.o.
  java.vm.version = 21.0.2+13-b375.1
  javax.swing.rebaseCssSizeMap = true
  jb.vmOptionsFile = ./consulo64.vmoptions
  jbr.virtualization.information = No virtualization detected
  jdk.debug = release
  jdk.module.main = consulo.desktop.awt.bootstrap
  jdk.module.main.class = consulo.desktop.awt.boot.main.Main
  jdk.module.path = ./platform/build3570/boot
  jna.loaded = true
  jna.nosys = true
  jna.platform.library.path = /usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib64:/lib64:/usr/lib:/lib:/usr/lib/x86_64-linux-gnu/libfakeroot
  jna.tmpdir = /root/.consulo_settings/system/tmp
  jnidispatch.path = /root/.consulo_settings/system/tmp/jna8533699565842402788.tmp
  line.separator = \n
  log4j.shutdownHookEnabled = false
  log4j2.messageFactory = org.apache.logging.log4j.message.SimpleMessageFactory
  native.encoding = UTF-8
  os.arch = amd64
  os.name = Linux
  os.version = 6.9.7-amd64
  path.separator = :
  stderr.encoding = UTF-8
  stdout.encoding = UTF-8
  sun.arch.data.model = 64
  sun.awt.datatransfer.timeout = 2000
  sun.awt.enableExtraMouseButtons = true
  sun.awt.exception.handler = consulo.desktop.awt.application.impl.AWTExceptionHandler
  sun.awt.noerasebackground = true
  sun.boot.library.path = /media/system76/WD-BACKUP/Hasibul\'s-World/IDE/Consulo/platform/build3570/jre/lib
  sun.cpu.endian = little
  sun.io.unicode.encoding = UnicodeLittle
  sun.io.useCanonCaches = false
  sun.java.command = consulo.desktop.awt.bootstrap/consulo.desktop.awt.boot.main.Main
  sun.java.launcher = SUN_STANDARD
  sun.java2d.d3d = false
  sun.java2d.noddraw = true
  sun.java2d.pmoffscreen = false
  sun.java2d.uiScale.enabled = true
  sun.jnu.encoding = UTF-8
  sun.management.compiler = HotSpot 64-Bit Tiered Compilers
  sun.nio.ch.bugLevel = 
  swing.bufferPerWindow = false
  user.country = US
  user.dir = /media/system76/WD-BACKUP/Hasibul\'s-World/IDE/Consulo
  user.home = /root
  user.language = en
  user.name = root
  user.timezone = Asia/Dhaka
 OS:
  name = Linux
  version = 6.9.7-amd64
  arch = amd64
 Env:
  ALL_JVM_ARGS = -Djava.security.manager=consulo.container.impl.securityManager.impl.ConsuloSecurityManager --add-opens=java.desktop/sun.awt=consulo.container.impl --add-opens=java.desktop/sun.swing=consulo.container.impl --add-opens=java.desktop/sun.awt.image=consulo.container.impl --add-opens=java.desktop/sun.java2d=consulo.container.impl --add-opens=java.desktop/sun.font=consulo.container.impl --add-opens=java.desktop/sun.awt.datatransfer=consulo.container.impl --add-opens=java.desktop/sun.awt.X11=consulo.container.impl --add-opens=java.desktop/java.awt=consulo.container.impl --add-opens=java.desktop/javax.swing=consulo.container.impl --add-opens=java.desktop/javax.swing.plaf.basic=consulo.container.impl --add-opens=java.base/java.lang=consulo.container.impl --add-opens=java.desktop/javax.swing.text.html=consulo.container.impl --add-opens=java.desktop/java.awt.peer=consulo.container.impl --add-opens=java.desktop/java.awt.event=consulo.container.impl --add-opens=java.desktop/com.apple.laf=consulo.container.impl --add-opens=java.desktop/com.apple.eawt=consulo.container.impl --add-opens=java.desktop/com.apple.eawt.event=consulo.container.impl  -Xms512m -Xmx1500m -XX:ReservedCodeCacheSize=240m -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=50 -XX:+HeapDumpOnOutOfMemoryError -Dawt.useSystemAAFontSettings=lcd  -Djb.vmOptionsFile="./consulo64.vmoptions" -Dconsulo.vm.options.file="./consulo64.vmoptions" -p "./platform/build3570/boot" -Dconsulo.module.path.boot=true -Dconsulo.home.path="./platform/build3570" -Didea.home.path="./platform/build3570" -Didea.properties.file="./consulo.properties" -Dconsulo.properties.file="./consulo.properties"   
  COLORTERM = truecolor
  CONSULO_HOME = ./platform/build3570
  DISPLAY = :0
  HOME = /root
  JDK = ./platform/build3570/jre
  LANG = en_US.UTF-8
  LC_ADDRESS = bn_BD
  LC_IDENTIFICATION = bn_BD
  LC_MEASUREMENT = bn_BD
  LC_MONETARY = bn_BD
  LC_NAME = bn_BD
  LC_NUMERIC = bn_BD
  LC_PAPER = bn_BD
  LC_TELEPHONE = bn_BD
  LC_TIME = bn_BD
  LD_LIBRARY_PATH = ./platform/build3570/bin:
  LOGNAME = root
  LS_COLORS = rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:
  MAIL = /var/mail/root
  MAIN_CLASS_NAME = -m consulo.desktop.awt.bootstrap/consulo.desktop.awt.boot.main.Main
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PWD = /media/system76/WD-BACKUP/Hasibul\'s-World/IDE/Consulo
  ROOT_DIR = .
  SHELL = /bin/bash
  SUDO_COMMAND = ./consulo.sh
  SUDO_GID = 1001
  SUDO_UID = 1000
  SUDO_USER = system76
  TERM = xterm-256color
  USER = root
  XAUTHORITY = /home/system76/.Xauthority
  XDG_CURRENT_DESKTOP = MATE

problem is: if i missed download plugin setup on first time run, cant install or download plugin later. id does not work, event delete .consulo folder from home dir. 
![Screenshot at 2024-09-02 00-29-03](https://github.com/user-attachments/assets/8d8c5338-e7b1-4199-bcd9-cabd06a9fdcb)

**Comment by coderhasib2021** [comment]
clicking refresh, view available plugin, doesn't work any.
![Screenshot from 2024-09-03 03-13-31](https://github.com/user-attachments/assets/a2f1ed06-9fa7-4b3b-b7d3-fef92a0651d7)

**Comment by VISTALL** [comment]
Good day. Can you show me this page?
![image](https://github.com/user-attachments/assets/a614b69d-343f-4231-996b-349f09d2ceff)

Also try to open this page in browser `https://api.consulo.io/repository/list?channel=nightly&platformVersion=SNAPSHOT`

**Comment by coderhasib2021** [comment]
Assalamu A'lakum wa Rahmatullah, I have tried all I know include above you mentioned maybe, but failed. As Last resort I have reinstall os, and this very painful you know. the problem was, in fresh os consulo ide setup automatically and show plugin install like this: 
![Screenshot from 2024-09-03 15-29-42](https://github.com/user-attachments/assets/9a365080-e039-4dbe-bda9-5f0f1828351d)
after selection window but if i missed or cancel or anything else it shows final/last/create new project window and then cant install necessary plugins anyhow. you can test yourself. even i have deleted .consulo where i found in home dir (dont know anywhere else has or not). please tell me any config edit to solve this prob and prevent future hassle.   thanks.

**Comment by VISTALL** [comment]
H,,. About Consulo directory - here list of them https://consulo.dev/basics/boot/boot.directories/

**Comment by coderhasib2021** [comment]
Linux

    Any:
        ${home-directory}/.consulo_settings
            config - configuration directory
            config/plugins - plugin directory
            system/log - log directory
where i have to change?

**Comment by VISTALL** [comment]
If you want make fresh install of Consulo - just delete `.consulo_settings`. (Fresh install of OS was premature decision).

Also inside Consulo (in empty project) you can open same Customize Dialog 
![image](https://github.com/user-attachments/assets/2a097e0f-5957-403e-b687-5cdebce3f8d8)

**Comment by coderhasib2021** [comment]
thanks. i will try.
