### ISSUE TITLE
add support for Dash integration

### ISSUE THREAD

**Issue by plandem** [consulo/consulo#74]
https://github.com/gdelmas/IntelliJDashPlugin

In that case user can use dash docsets for projects. Maybe there is no need to port plugin, but just integrate Dash directly into the Consulo with support of 'docset' keywords for project (User can install alot docsets for Dash, but want to use only few for that projects).

P.S.: From official info at Dash to integrate to any App:

Dash can be integrated with any app which supports OS X System Services or which can open a custom URL scheme:

1. System Service. There is a "Look Up in Dash" system service. To use it: select text in any app, right click and go to Services > "Look Up in Dash". You can also set a keyboard shortcut for this system service in the General tab of this window.

2. URL Scheme. Dash implements a custom URL scheme which you can use to allow your text editors and IDEs to initiate a search within Dash. This also works with docset keywords (defined in Preferences > Docsets) or search profile keyword triggers (defined by clicking on the loupe icon of the main search field). Keywords are optional. 
The URL Scheme is: "dash://keyword:{query}".

**Comment by cupsster** [comment]
I do not get it if it was working and you mention it is working in windows as well where can one find it? I wasted 4h today to get it working, I can download plugin but it won't install and does not show in any menu..

**Comment by VISTALL** [comment]
Hi. Working on fix

**Comment by VISTALL** [comment]
Fixed

**Comment by cupsster** [comment]
How to enable then, I just can't get it working and lots of errors/crashes starting to popup.. I'm thinking of reinstalling whole thing from scratch... again.

**Comment by cupsster** [comment]
OK as last resort I've done complete clean reinstall. That helped. Now it is working I can setup all custom options now. Might be best idea to focus on autoupdate. Thank you again VISTALL you my hero of the day :3

**Comment by VISTALL** [comment]
You need only update Dash plugin. If you get errors - think you have some old plugins or old Consulo build.
