### ISSUE TITLE
ideavim plugin dependency

### ISSUE THREAD

**Issue by eyveer** [consulo/consulo#77]
I've tried to install IDEAvim plugin without success due to missing com.intellij.modules.lang.

Is there a way to use IDEAvim plugin with Consulo?

**Comment by VISTALL** [comment]
IntelliJ plugins dont work with Consulo. Need port it.

**Comment by VISTALL** [comment]
Me ported it - after some time, it ill available. But maybe it require update consulo when it ill 576 build
