### ISSUE TITLE
Install Plugins https://wakatime.com/

### ISSUE THREAD

**Issue by Avatarchik** [consulo/consulo#85]
How to install a plugin? https://wakatime.com/
Or how to add a default repository plugins
Or this plugin from IntelliJ IDEA not fit?

**Comment by VISTALL** [comment]
Consulo dont supported IntelliJ plugins, due API difference. And different plugin sets

I saw - plugin is open, and i can move it to Consulo.

Thanks

**Comment by VISTALL** [comment]
https://github.com/wakatime/jetbrains-wakatime

**Comment by VISTALL** [comment]
I watch their code and it so bad. Me only converted plugin, but i will not fix any bugs in this plugins.

Link: https://drive.google.com/file/d/0BwdC25ghEUn_ZkEwVUl1Y3VFYVk/view?usp=sharing
