### ISSUE TITLE
Tricky check for explicit IDEA_JDK on MAC

### ISSUE THREAD

**Issue by clumsy** [consulo/consulo#93]
``` java
void appendBundle(NSString *path, NSMutableArray *sink) {
    if ([path hasSuffix:@".jdk"] || [path hasSuffix:@".jre"]) {
        NSBundle *bundle = [NSBundle bundleWithPath:path];
        if (bundle != nil) {
            [sink addObject:bundle];
        }
    }
}
```

checking whether the folder has a certain suffix is not straight-forward and error-prone.

**Comment by VISTALL** [comment]
Currenty i cant build consulo mac launcher. Idk - but current launcher is old, maybe need merge from JB repo, but it change layout of distribution, it can broke all :(

**Comment by VISTALL** [comment]
Ah. And - i want change IDEA_JDK, to CONSULO_JDK or CONSULO_JRE. It already chaged at Windows launcher.

For Consulo start dont need JDK, JRE will work too:)

**Comment by VISTALL** [comment]
obsolete for new mac launcher
