### ISSUE TITLE
Heap pollution in ProgressManagerImpl

### ISSUE THREAD

**Issue by clumsy** [consulo/consulo#98]
Every 10 milliseconds a scheduled task is executed that iterates nonStandardIndicators in order to check their status in a dedicated thread. For that 2 objects are created behind the scenes for ConcurrentHashMultiset's iterator.
Suggestions:
* use Trove's THashSet as Multiset semantics is not used by ProgressManagerImpl
* use forEach to iterate over nonStandardIndicators after flushing current collection state

**Comment by VISTALL** [comment]
Interest code. Why used ConcurrentHashMultiset - i dont known for now

**Comment by clumsy** [comment]
Me neither. It may have been used in some previous version of that class, but in the current one it's an overkill.

**Comment by VISTALL** [comment]
It have used **ConcurrentHashSet** before https://github.com/JetBrains/intellij-community/commit/e33bacad3801e85d7a66c072b99062c1250138e6

Really dont known why they change it

**Comment by clumsy** [comment]
ConcurrentHashMultiset adds this count(T) that indicates how many times the entry was added, it uses this count in order to check whether it should provide an immutable getter for values with count > 1 or something like that.
ConcurrentHashSet provides an iterator that will not throw us a ConcurrentModificationException, but still will have to create a new object for the iterator.
With Trove we can iterate without the iterator. For an operation that is executed every 10 milliseconds I would prefer an iterator less Trove.

**Comment by VISTALL** [comment]
It used custom ConcurrentHashSet  - need only make optimization for **iterator()** method

I dislike using Trove in concurrent state

**Comment by VISTALL** [comment]
No sence for using it. It used as temp container >.<

**Comment by clumsy** [comment]
Sorry, I cannot understand what you are suggesting then.

**Comment by VISTALL** [comment]
Sorry

I said about **ConcurrentHashMultiset **. In code used only **add, remove, iterator** methods.

**Comment by clumsy** [comment]
Right. Though I see no problem using Trove in here. It looks to me we only need safe publishing and calling a function on every element. Do you have any concerns about that?
We can use vanilla arrays, but I think Trove will be much more readable.

**Comment by VISTALL** [comment]
It will be good, but need sync every 10 ms is bad.

Me thinking about com.intellij.util.containers.ContainerUtil#createConcurrentList

It create object ot LockFreeCopyOnWriteArrayList, where **iterator** method is optimized.

Stops only **Set** vs **List**, i cant say consequences

**Comment by VISTALL** [comment]
Oh forgot about **addIfAbsent**

**Comment by VISTALL** [comment]
I thk - need add function, forEach - dont need create Iterator object every 10 ms

**Comment by VISTALL** [comment]
Check https://github.com/consulo/consulo/tree/%2398 branch

**Comment by clumsy** [comment]
Looks good. It seems like adds are not that frequent so it makes sense to keep it a set and only make a copy when you add.
I only suggest remaining Processor. It's too overloaded word. What do you think of remaining it to ForEach?

**Comment by VISTALL** [comment]
А теперь можно повторить по русски? До конца суть понять не могу.

**Comment by clumsy** [comment]
I'd rather use English on the GitHub, but you can email me: alexander.jipa@gmail.com
But again, looks good! I suggest renaming Processor class (in the forEach) to ForEach or some other not that overloaded word.

**Comment by VISTALL** [comment]
agree

**Comment by VISTALL** [comment]
done
